### ISSUE TITLE
Calling Crystal functions from C 

### ISSUE THREAD

**Issue by syalon** [manastech/crystal#1219] opened 2015-08-18 03:38 UTC
how do I invoke crystal method from c?

**Comment by jhass** [comment] 2015-08-18 08:26
There's no first class support for this and we're not sure if there ever will be, for now you can see a PoC for this at https://gist.github.com/k2b6s9j/3bd3aadd71db206e828f

Duplicate of #921

**Closed** 2015-08-18 21:41 UTC
