### ISSUE TITLE
Crash: Array of Object

### ISSUE THREAD

**Issue by stefanwille** [manastech/crystal#469] opened 2015-03-09 11:18 UTC
Hi,

I am building a Redis client for Crystal, and so far I like the experience a lot.

Currently I am stuck at declaring an array. I have a method than parses a Redis response string as an object and returns it. If Redis responds with an array, it can be an array of anything - it can contain strings, integers, nil or others arrays. Therefore I want to define it as an array of Object. But I get a crash when I do so:

-------- 
File array-of-objects.cr:

my_array = [] of Object
my_array << 1
puts my_array

----------

$ crystal run array-of-objects.cr

cast to Crystal::NonGenericOrGenericClassInstanceType failed
*raise<String>:NoReturn +70 [4312275542]
*Crystal::VirtualType@Crystal::VirtualTypeLookup#lookup_matches<Crystal::VirtualType, Crystal::CallSignature, Crystal::VirtualType, Crystal::VirtualType>:Crystal::Matches +6723 [4315928499]
*Crystal::Call#lookup_matches_with_signature<Crystal::Call, Crystal::Type+, Crystal::CallSignature>:Crystal::Matches +1385 [4316685897]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +1189 [4316667269]
*Crystal::Call#lookup_matches_in<Crystal::Call, Crystal::UnionType+, Array(Crystal::Type+)>:Array(Crystal::Def+) +840 [4315552168]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Block>:(Bool | Nil) +1630 [4315125166]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +78539 [4313523259]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Block>:(Bool | Nil) +1630 [4315125166]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +78539 [4313523259]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Block>:(Bool | Nil) +1630 [4315125166]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +78539 [4313523259]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Block>:(Bool | Nil) +1630 [4315125166]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +78539 [4313523259]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +57033 [4313501753]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Block>:(Bool | Nil) +1630 [4315125166]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +78539 [4313523259]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +643 [4313445363]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +15142 [4313459862]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +643 [4313445363]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#instantiate<Crystal::Call, Crystal::Matches, Crystal::Type+, Nil>:Array(Crystal::Def+) +11907 [4317143395]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Type+, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +16019 [4316682099]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Call#lookup_matches_in_type<Crystal::Call, Crystal::Program, Array(Crystal::Type+), Nil, String>:Array(Crystal::Def+) +17318 [4315569702]
*Crystal::Call#recalculate<Crystal::Call>:Array(Crystal::Def+)? +2393 [4312457961]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Call>:Bool +9673 [4313905097]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2731 [4313447451]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +43138 [4313487858]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4243 [4314112371]
*Crystal::Command::run_command<Array(String)>:Nil +304 [4312297024]
*Crystal::Command::run<Array(String)>:(Crystal::Compiler::Result | File | Bool | CFileIO | Nil) +7839 [4312285183]
__crystal_main +10046 [4312273470]
main +48 [4312276096]

Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
-------

Please help so that I can continue.

**Comment by jhass** [comment] 2015-03-09 11:20
As a workaround try to use (an alias to) a union of all the possible type. You can find an example in stdlib of that technique in the [json parser](https://github.com/manastech/crystal/blob/master/src/json/json.cr#L11)

**Comment by stefanwille** [comment] 2015-03-09 11:44
Looks great, and thanks for the fast reply!
Now I do this:
-----
alias Type = Nil | Number | String | Array(Type)
my_array = [] of Type
my_array << 1
puts my_array
----
and it doesn't work as expected:
----
$ crystal run array-of-objects.cr
[
----
To debug this, I slightly modified my code and got a real crash:
------
alias Type = Nil | Number | String | Array(Type)
my_array = [] of Type
my_array << 1
puts my_array[0]
------
$ crystal run array-of-objects.cr
Program terminated abnormally with error code: 11

**Comment by jhass** [comment] 2015-03-09 12:00
That looks like a second bug, maybe open another issue :)

PS: [Small formatting Github protip](https://help.github.com/articles/github-flavored-markdown/#fenced-code-blocks) ;)

**Comment by asterite** [comment] 2015-03-09 14:16
Hi @stefanwille !

This is a duplicate of #247 . We should fix this soon, every newcomer trips with this :-) . We'll either give a compile error when using Object (or Value, or Reference) as a generic type for now and later think how to implement it (if we want to do this).

The second bug, `[] of Number | ...` should work, I'll fix it.

By the way, [there's a Redis client already](https://github.com/manastech/crystal_redis). I'm using it in one of our apps and it's working pretty well. [Here's the type](https://github.com/manastech/crystal_redis/blob/master/src/protocol.cr#L2) I use for the protocol. As you can see, I didn't use `Number`, I used `Int64`, because that's the type [guaranteed to be returned](http://redis.io/topics/protocol#resp-integers) by the protocol. It's always good to be as specific as you can with your types, not just because the compiler blows right now, but because you will get better compile-time errors and more performance that way.

That Redis client is very young and has very few commands, so feel free to fork it and add more functionality to it :-)

**Comment by stefanwille** [comment] 2015-03-11 11:53
Thanks for the help!

**Comment by asterite** [comment] 2015-05-02 15:04
In 0.7.1 `[] of Object` is not allowed anymore, so I'll close this for now.

**Closed by asterite** 2015-05-02 15:04 UTC
Labels: bug
