### ISSUE TITLE
Travis CI build failed - asked to report

### ISSUE THREAD

**Issue by ukd1** [manastech/crystal#1168] opened 2015-08-13 02:54 UTC
https://travis-ci.org/dhruvrajvanshi/Moonshine/builds/75374007 - I found it when making dhruvrajvanshi/Moonshine#17

```
Using worker: worker-linux-docker-2f148ac6.prod.travis-ci.org:travis-linux-2
system_info
Build system information
Build language: crystal
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
LLVM version
clang version 3.4 (tags/RELEASE_34/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
Pre-installed Ruby versions
ruby-1.9.3-p551
Pre-installed Node.js versions
v0.10.36
Pre-installed Go versions
1.4.1
Redis version
redis-server 2.8.19
riak version
2.0.2
MongoDB version
MongoDB 2.4.12
CouchDB version
couchdb 1.6.1
Neo4j version
1.9.4
RabbitMQ Version
3.4.3
ElasticSearch version
1.4.0
Installed Sphinx versions
2.0.10
2.1.9
2.2.6
Default Sphinx version
2.2.6
Installed Firefox version
firefox 31.0esr
PhantomJS version
1.9.8
ant -version
Apache Ant(TM) version 1.8.2 compiled on December 3 2011
mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T17:29:23+00:00)
Maven home: /usr/local/maven
Java version: 1.7.0_76, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "3.13.0-29-generic", arch: "amd64", family: "unix"
crystal_install
Installing Crystal
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.JDP19DjDZW --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net
gpg: key 7CC06B54: public key "Crystal Distribution Signing <dist-sign@crystal-lang.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Get:1 http://downloads-distro.mongodb.org dist Release.gpg [490 B]
Get:2 http://downloads-distro.mongodb.org dist Release [2,040 B]
Get:3 http://downloads-distro.mongodb.org dist/10gen amd64 Packages [30.1 kB]
Get:4 http://security.ubuntu.com precise-security Release.gpg [198 B]
Get:5 http://downloads-distro.mongodb.org dist/10gen i386 Packages [29.5 kB]
Hit http://us.archive.ubuntu.com precise Release.gpg
Get:6 http://us.archive.ubuntu.com precise-updates Release.gpg [198 B]
Get:7 http://us.archive.ubuntu.com precise-backports Release.gpg [198 B]
Get:8 http://security.ubuntu.com precise-security Release [54.3 kB]
Hit http://us.archive.ubuntu.com precise Release
Get:9 http://us.archive.ubuntu.com precise-updates Release [196 kB]
Get:10 http://dist.crystal-lang.org crystal Release.gpg [836 B]
Get:11 http://apt.postgresql.org precise-pgdg Release.gpg [819 B]
Get:12 http://security.ubuntu.com precise-security/main Sources [168 kB]
Get:13 http://us.archive.ubuntu.com precise-backports Release [54.3 kB]
Hit http://us.archive.ubuntu.com precise/main Sources
Hit http://us.archive.ubuntu.com precise/restricted Sources
Hit http://us.archive.ubuntu.com precise/universe Sources
Hit http://us.archive.ubuntu.com precise/multiverse Sources
Hit http://us.archive.ubuntu.com precise/main amd64 Packages
Hit http://us.archive.ubuntu.com precise/restricted amd64 Packages
Hit http://us.archive.ubuntu.com precise/universe amd64 Packages
Hit http://us.archive.ubuntu.com precise/multiverse amd64 Packages
Hit http://us.archive.ubuntu.com precise/main i386 Packages
Get:14 http://security.ubuntu.com precise-security/restricted Sources [3,565 B]
Get:15 http://security.ubuntu.com precise-security/universe Sources [50.9 kB]
Get:16 http://security.ubuntu.com precise-security/multiverse Sources [2,060 B]
Get:17 http://security.ubuntu.com precise-security/main amd64 Packages [692 kB]
Get:18 http://apt.postgresql.org precise-pgdg Release [36.5 kB]
Hit http://us.archive.ubuntu.com precise/restricted i386 Packages
Get:19 http://dist.crystal-lang.org crystal Release [1,628 B]
Hit http://us.archive.ubuntu.com precise/universe i386 Packages
Hit http://us.archive.ubuntu.com precise/multiverse i386 Packages
Get:20 http://us.archive.ubuntu.com precise-updates/main Sources [603 kB]
Get:21 http://security.ubuntu.com precise-security/restricted amd64 Packages [14.9 kB]
Get:22 http://security.ubuntu.com precise-security/universe amd64 Packages [158 kB]
Get:23 http://security.ubuntu.com precise-security/multiverse amd64 Packages [2,509 B]
Get:24 http://security.ubuntu.com precise-security/main i386 Packages [754 kB]
Get:25 http://us.archive.ubuntu.com precise-updates/restricted Sources [8,152 B]
Get:26 http://us.archive.ubuntu.com precise-updates/universe Sources [150 kB]
Get:27 http://us.archive.ubuntu.com precise-updates/multiverse Sources [10.2 kB]
Get:28 http://us.archive.ubuntu.com precise-updates/main amd64 Packages [1,200 kB]
Get:29 http://security.ubuntu.com precise-security/restricted i386 Packages [14.9 kB]
Get:30 http://security.ubuntu.com precise-security/universe i386 Packages [168 kB]
Hit http://ppa.launchpad.net precise Release.gpg
Hit http://ppa.launchpad.net precise Release.gpg
Get:31 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:32 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:33 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:34 http://ppa.launchpad.net precise Release.gpg [316 B]
Get:35 http://dist.crystal-lang.org crystal/main amd64 Packages [372 B]
Get:36 http://security.ubuntu.com precise-security/multiverse i386 Packages [2,692 B]
Get:37 http://us.archive.ubuntu.com precise-updates/restricted amd64 Packages [20.8 kB]
Get:38 http://us.archive.ubuntu.com precise-updates/universe amd64 Packages [345 kB]
Get:39 http://apt.postgresql.org precise-pgdg/main amd64 Packages [70.1 kB]
Get:40 http://us.archive.ubuntu.com precise-updates/multiverse amd64 Packages [18.7 kB]
Get:41 http://us.archive.ubuntu.com precise-updates/main i386 Packages [1,263 kB]
Get:42 http://us.archive.ubuntu.com precise-updates/restricted i386 Packages [20.7 kB]
Get:43 http://us.archive.ubuntu.com precise-updates/universe i386 Packages [356 kB]
Get:44 http://dist.crystal-lang.org crystal/main i386 Packages [371 B]
Get:45 http://us.archive.ubuntu.com precise-updates/multiverse i386 Packages [18.9 kB]
Get:46 http://us.archive.ubuntu.com precise-backports/main Sources [5,479 B]
Get:47 http://us.archive.ubuntu.com precise-backports/restricted Sources [40 B]
Get:48 http://us.archive.ubuntu.com precise-backports/universe Sources [50.5 kB]
Get:49 http://us.archive.ubuntu.com precise-backports/multiverse Sources [5,886 B]
Get:50 http://us.archive.ubuntu.com precise-backports/main amd64 Packages [5,591 B]
Get:51 http://us.archive.ubuntu.com precise-backports/restricted amd64 Packages [40 B]
Hit http://ppa.launchpad.net precise Release
Hit http://ppa.launchpad.net precise Release
Get:52 http://ppa.launchpad.net precise Release [12.9 kB]
Get:53 http://us.archive.ubuntu.com precise-backports/universe amd64 Packages [54.8 kB]
Get:54 http://us.archive.ubuntu.com precise-backports/multiverse amd64 Packages [5,459 B]
Get:55 http://us.archive.ubuntu.com precise-backports/main i386 Packages [5,586 B]
Get:56 http://us.archive.ubuntu.com precise-backports/restricted i386 Packages [40 B]
Get:57 http://us.archive.ubuntu.com precise-backports/universe i386 Packages [54.6 kB]
Get:58 http://us.archive.ubuntu.com precise-backports/multiverse i386 Packages [5,437 B]
Get:59 http://apt.postgresql.org precise-pgdg/main i386 Packages [70.0 kB]
Get:60 http://ppa.launchpad.net precise Release [12.9 kB]
Get:61 http://ppa.launchpad.net precise Release [12.9 kB]
Get:62 http://ppa.launchpad.net precise Release [13.0 kB]
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Hit http://ppa.launchpad.net precise/main amd64 Packages
Hit http://ppa.launchpad.net precise/main i386 Packages
Get:63 http://ppa.launchpad.net precise/main amd64 Packages [610 B]
Get:64 http://ppa.launchpad.net precise/main i386 Packages [613 B]
Get:65 http://ppa.launchpad.net precise/main amd64 Packages [1,195 B]
Get:66 http://ppa.launchpad.net precise/main i386 Packages [828 B]
Get:67 http://ppa.launchpad.net precise/main amd64 Packages [36.7 kB]
Get:68 http://ppa.launchpad.net precise/main i386 Packages [36.7 kB]
Get:69 http://ppa.launchpad.net precise/main amd64 Packages [3,087 B]
Get:70 http://ppa.launchpad.net precise/main i386 Packages [3,087 B]
Fetched 6,925 kB in 3s (1,863 kB/s)
Reading package lists... Done
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_main_source_Sources.gz is not what the server reported 5479 5482
W: Size of file /var/lib/apt/lists/us.archive.ubuntu.com_ubuntu_dists_precise-backports_multiverse_source_Sources.gz is not what the server reported 5886 5888
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_rwky_redis_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 610 612
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-amd64_Packages.gz is not what the server reported 36669 36677
W: Size of file /var/lib/apt/lists/ppa.launchpad.net_ubuntugis_ppa_ubuntu_dists_precise_main_binary-i386_Packages.gz is not what the server reported 36729 36733
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  crystal
0 upgraded, 1 newly installed, 0 to remove and 200 not upgraded.
Need to get 10.8 MB of archives.
After this operation, 32.8 MB of additional disk space will be used.
Get:1 http://dist.crystal-lang.org/apt/ crystal/main crystal amd64 0.7.5-1 [10.8 MB]
Fetched 10.8 MB in 0s (21.2 MB/s)
Selecting previously unselected package crystal.
(Reading database ... 71420 files and directories currently installed.)
Unpacking crystal (from .../crystal_0.7.5-1_amd64.deb) ...
You're about to install crystal!
Setting up crystal (0.7.5-1) ...
git.checkout
0.13s$ git clone --depth=50 git://github.com/dhruvrajvanshi/Moonshine.git dhruvrajvanshi/Moonshine
Cloning into 'dhruvrajvanshi/Moonshine'...
remote: Counting objects: 455, done.
remote: Compressing objects: 100% (229/229), done.
remote: Total 455 (delta 224), reused 449 (delta 218), pack-reused 0
Receiving objects: 100% (455/455), 69.89 KiB | 0 bytes/s, done.
Resolving deltas: 100% (224/224), done.
Checking connectivity... done.
$ cd dhruvrajvanshi/Moonshine
0.54s$ git fetch origin +refs/pull/17/merge:
remote: Counting objects: 7, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7 (delta 4), reused 6 (delta 4), pack-reused 0
Unpacking objects: 100% (7/7), done.
From git://github.com/dhruvrajvanshi/Moonshine
 * branch            refs/pull/17/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
This job is running on container-based infrastructure, which does not allow use of 'sudo', setuid and setguid executables.
If you require sudo, add 'sudo: required' to your .travis.yml
See http://docs.travis-ci.com/user/workers/container-based-infrastructure/ for details.
Crystal for Travis-CI is not officially supported, but is community maintained.
Please file any issues using the following link
  https://github.com/travis-ci/travis-ci/issues/new?labels=community:crystal
and mention `@asterite`, `@jhass`, `@waj` and `@will` in the issue
$ crystal --version
Crystal 0.7.5 [2a33a87] (Thu Jul 30 17:32:32 UTC 2015)
0.28s$ crystal spec
; ModuleID = 'main_module'
%String = type { i32, i32, i32, i8 }
%"Array(Int32)" = type { i32, i32, i32, i32* }
%Fiber = type { i32, i8*, %"(( -> Nil) | ( -> Void))", i8*, i8*, i8*, %Fiber*, %Fiber* }
%"(( -> Nil) | ( -> Void))" = type { i32, [2 x i64] }
%"Array(Spec::Context+)" = type { i32, i32, i32, i32** }
%"struct.LibABI::UnwindException" = type { i64, i64, i64, i64, i64, i32 }
@"'finalize'" = private constant { i32, i32, i32, [9 x i8] } { i32 1, i32 8, i32 8, [9 x i8] c"finalize\00" }
@"'success'" = private constant { i32, i32, i32, [8 x i8] } { i32 1, i32 7, i32 7, [8 x i8] c"success\00" }
@"'fail'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"fail\00" }
@"'error'" = private constant { i32, i32, i32, [6 x i8] } { i32 1, i32 5, i32 5, [6 x i8] c"error\00" }
@"'pending'" = private constant { i32, i32, i32, [8 x i8] } { i32 1, i32 7, i32 7, [8 x i8] c"pending\00" }
@"'green'" = private constant { i32, i32, i32, [6 x i8] } { i32 1, i32 5, i32 5, [6 x i8] c"green\00" }
@"'red'" = private constant { i32, i32, i32, [4 x i8] } { i32 1, i32 3, i32 3, [4 x i8] c"red\00" }
@"'yellow'" = private constant { i32, i32, i32, [7 x i8] } { i32 1, i32 6, i32 6, [7 x i8] c"yellow\00" }
@"'black'" = private constant { i32, i32, i32, [6 x i8] } { i32 1, i32 5, i32 5, [6 x i8] c"black\00" }
@"'blue'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"blue\00" }
@"'magenta'" = private constant { i32, i32, i32, [8 x i8] } { i32 1, i32 7, i32 7, [8 x i8] c"magenta\00" }
@"'cyan'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"cyan\00" }
@"'light_gray'" = private constant { i32, i32, i32, [11 x i8] } { i32 1, i32 10, i32 10, [11 x i8] c"light_gray\00" }
@"'dark_gray'" = private constant { i32, i32, i32, [10 x i8] } { i32 1, i32 9, i32 9, [10 x i8] c"dark_gray\00" }
@"'light_red'" = private constant { i32, i32, i32, [10 x i8] } { i32 1, i32 9, i32 9, [10 x i8] c"light_red\00" }
@"'light_green'" = private constant { i32, i32, i32, [12 x i8] } { i32 1, i32 11, i32 11, [12 x i8] c"light_green\00" }
@"'light_yellow'" = private constant { i32, i32, i32, [13 x i8] } { i32 1, i32 12, i32 12, [13 x i8] c"light_yellow\00" }
@"'light_blue'" = private constant { i32, i32, i32, [11 x i8] } { i32 1, i32 10, i32 10, [11 x i8] c"light_blue\00" }
@"'light_magenta'" = private constant { i32, i32, i32, [14 x i8] } { i32 1, i32 13, i32 13, [14 x i8] c"light_magenta\00" }
@"'light_cyan'" = private constant { i32, i32, i32, [11 x i8] } { i32 1, i32 10, i32 10, [11 x i8] c"light_cyan\00" }
@"'white'" = private constant { i32, i32, i32, [6 x i8] } { i32 1, i32 5, i32 5, [6 x i8] c"white\00" }
@"'get'" = private constant { i32, i32, i32, [4 x i8] } { i32 1, i32 3, i32 3, [4 x i8] c"get\00" }
@"'call'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"call\00" }
@"'to_s'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"to_s\00" }
@":symbol_table" = global [24 x %String*] [%String* bitcast ({ i32, i32, i32, [9 x i8] }* @"'finalize'" to %String*), %String* bitcast ({ i32, i32, i32, [8 x i8] }* @"'success'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'fail'" to %String*), %String* bitcast ({ i32, i32, i32, [6 x i8] }* @"'error'" to %String*), %String* bitcast ({ i32, i32, i32, [8 x i8] }* @"'pending'" to %String*), %String* bitcast ({ i32, i32, i32, [6 x i8] }* @"'green'" to %String*), %String* bitcast ({ i32, i32, i32, [4 x i8] }* @"'red'" to %String*), %String* bitcast ({ i32, i32, i32, [7 x i8] }* @"'yellow'" to %String*), %String* bitcast ({ i32, i32, i32, [6 x i8] }* @"'black'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'blue'" to %String*), %String* bitcast ({ i32, i32, i32, [8 x i8] }* @"'magenta'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'cyan'" to %String*), %String* bitcast ({ i32, i32, i32, [11 x i8] }* @"'light_gray'" to %String*), %String* bitcast ({ i32, i32, i32, [10 x i8] }* @"'dark_gray'" to %String*), %String* bitcast ({ i32, i32, i32, [10 x i8] }* @"'light_red'" to %String*), %String* bitcast ({ i32, i32, i32, [12 x i8] }* @"'light_green'" to %String*), %String* bitcast ({ i32, i32, i32, [13 x i8] }* @"'light_yellow'" to %String*), %String* bitcast ({ i32, i32, i32, [11 x i8] }* @"'light_blue'" to %String*), %String* bitcast ({ i32, i32, i32, [14 x i8] }* @"'light_magenta'" to %String*), %String* bitcast ({ i32, i32, i32, [11 x i8] }* @"'light_cyan'" to %String*), %String* bitcast ({ i32, i32, i32, [6 x i8] }* @"'white'" to %String*), %String* bitcast ({ i32, i32, i32, [4 x i8] }* @"'get'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'call'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'to_s'" to %String*)]
@ARGC_UNSAFE = global i32 0
@ARGV_UNSAFE = global i8** null
@"LibC::PROT_READ" = constant i32 1
@"LibC::PROT_WRITE" = constant i32 2
@"LibC::MAP_PRIVATE" = constant i32 2
@"LibC::MAP_ANON" = constant i32 32
@"'unwind'" = private constant { i32, i32, i32, [7 x i8] } { i32 1, i32 6, i32 6, [7 x i8] c"unwind\00" }
@"Unwind::REG_IP" = constant i32 -1
@"'pthread'" = private constant { i32, i32, i32, [8 x i8] } { i32 1, i32 7, i32 7, [8 x i8] c"pthread\00" }
@"'gc'" = private constant { i32, i32, i32, [3 x i8] } { i32 1, i32 2, i32 2, [3 x i8] c"gc\00" }
@"Int::DIGITS_DOWNCASE" = constant %String* bitcast ({ i32, i32, i32, [37 x i8] }* @"'0123456789abcdefghi...'" to %String*)
@"'0123456789abcdefghi...'" = private constant { i32, i32, i32, [37 x i8] } { i32 1, i32 36, i32 36, [37 x i8] c"0123456789abcdefghijklmnopqrstuvwxyz\00" }
@"Int::DIGITS_UPCASE" = constant %String* bitcast ({ i32, i32, i32, [37 x i8] }* @"'0123456789ABCDEFGHI...'" to %String*)
@"'0123456789ABCDEFGHI...'" = private constant { i32, i32, i32, [37 x i8] } { i32 1, i32 36, i32 36, [37 x i8] c"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\00" }
@"String::TYPE_ID" = constant i32 1
@"String::HEADER_SIZE" = constant i32 trunc (i64 mul nuw (i64 ptrtoint (i32* getelementptr (i32* null, i32 1) to i64), i64 3) to i32)
@"String::CHAR_TO_DIGIT" = global [256 x i8] undef
@"Time::TicksMask" = constant i64 4611686018427387903
@"Time::MAX_VALUE_TICKS" = constant i64 3155378975999999999
@"Time::DAYS_MONTH" = external global %"Array(Int32)"*
define internal i32* @__crystal_main(i32 %argc, i8** %argv) {
alloca:
  %__temp_85 = alloca %Fiber*
  %__temp_108 = alloca %"Array(Spec::Context+)"*
  %__temp_109 = alloca i32**
  %table = alloca [256 x i8]
  %0 = alloca [256 x i8]
  %i = alloca i8
  %i1 = alloca i8
  %i2 = alloca i8
  %i3 = alloca i8
  %__temp_222 = alloca %"Array(Int32)"*
  %__temp_223 = alloca i32*
entry:                                            ; No predecessors!
  store i32 %argc, i32* @ARGC_UNSAFE
  store i8** %argv, i8*** @ARGV_UNSAFE
  %1 = call [256 x i8] @"*StaticArray(Int8, 256)::new<StaticArray(Int8, 256):Class, Int8>:StaticArray(Int8, 256)"(i32 778, i8 -1)
  store [256 x i8] %1, [256 x i8]* %0
  %2 = load [256 x i8]* %0
  store [256 x i8] %2, [256 x i8]* %table
  store i8 0, i8* %i1
  br label %while
while:                                            ; preds = %body, %entry
  %3 = load i8* %i1
  %4 = icmp slt i8 %3, 10
  br i1 %4, label %body, label %exit
body:                                             ; preds = %while
  %5 = load i8* %i1
  store i8 %5, i8* %i
  %6 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
  %7 = load i8* %i
  %8 = sext i8 %7 to i32
  %9 = add i32 48, %8
  %10 = load i8* %i
  %11 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %6, i32 %9, i8 %10)
  %12 = load i8* %i1
  %13 = sext i8 %12 to i32
  %14 = add i32 %13, 1
  %15 = trunc i32 %14 to i8
  store i8 %15, i8* %i1
  br label %while
exit:                                             ; preds = %while
  store i8 0, i8* %i3
  br label %while4
while4:                                           ; preds = %body5, %exit
  %16 = load i8* %i3
  %17 = icmp slt i8 %16, 26
  br i1 %17, label %body5, label %exit6
body5:                                            ; preds = %while4
  %18 = load i8* %i3
  store i8 %18, i8* %i2
  %19 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
  %20 = load i8* %i2
  %21 = sext i8 %20 to i32
  %22 = add i32 65, %21
  %23 = load i8* %i2
  %24 = sext i8 %23 to i32
  %25 = add i32 %24, 10
  %26 = trunc i32 %25 to i8
  %27 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %19, i32 %22, i8 %26)
  %28 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
  %29 = load i8* %i2
  %30 = sext i8 %29 to i32
  %31 = add i32 97, %30
  %32 = load i8* %i2
  %33 = sext i8 %32 to i32
  %34 = add i32 %33, 10
  %35 = trunc i32 %34 to i8
  %36 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %28, i32 %31, i8 %35)
  %37 = load i8* %i3
  %38 = sext i8 %37 to i32
  %39 = add i32 %38, 1
  %40 = trunc i32 %39 to i8
  store i8 %40, i8* %i3
  br label %while4
exit6:                                            ; preds = %while4
  %41 = load [256 x i8]* %table
  store [256 x i8] %41, [256 x i8]* @"String::CHAR_TO_DIGIT"
}
declare i32 @printf(i8*, ...)
declare i8* @__crystal_malloc(i32)
declare i8* @__crystal_realloc(i8*, i32)
; Function Attrs: noreturn
declare void @__crystal_raise(%"struct.LibABI::UnwindException"*) #0
declare i8* @__crystal_malloc_atomic(i32)
declare [256 x i8] @"*StaticArray(Int8, 256)::new<StaticArray(Int8, 256):Class, Int8>:StaticArray(Int8, 256)"(i32, i8)
declare i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]*)
declare i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8*, i32, i8)
attributes #0 = { noreturn }
Bug: [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] at /opt/crystal/src/time/time.cr:36:16 should have been expanded
*raise<String>:NoReturn +70 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +25037 [0]
*Crystal::CodeGenVisitor#initialize_const<Crystal::CodeGenVisitor, Crystal::Const, String>:(Nil | LLVM::Value) +737 [0]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:(Nil | Bool) +534 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2554 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1421 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2787 [0]
*Crystal::Program#build<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +187 [0]
*Crystal::Compiler#build<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Int32 | Bool) +3466 [0]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +5123 [0]
*Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +16667 [0]
main +17469 [0]
__libc_start_main +237 [0]
_start +41 [0]
Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues
The command "crystal spec" exited with 1.
Done. Your build exited with 1.
```

**Comment by asterite** [comment] 2015-08-13 13:09
Thanks. This is a duplicate of #1028, try compiling with a compiler built with HEAD.

**Closed by asterite** 2015-08-13 13:09 UTC
