### ISSUE TITLE
Typing syntax

### ISSUE THREAD

**Issue by lepieru** [manastech/crystal#1907] opened 2015-11-25 22:47 UTC
To type something in Crystal, it sometimes looks like `variable : Type` :

``` ruby
def a_method(arg : Type)
…
rescue exception : ExceptionType
…
# maybe I missed a cool example
```

However, it's different when a variable is declared with a type restriction :

``` ruby
variable :: Type
# or
variable::Type
```

It seems very similar to the namespace navigation, e.g. `Entites::Dog`.

What was the motivation of this choice ?

**Comment by jhass** [comment] 2015-11-25 23:07
Those are different operations. One is a restriction of which types the argument can have, the other is a declaration, that actually allocates the variable on the stack.

**Comment by lepieru** [comment] 2015-11-25 23:45
Yes of course, but all of this is about typing (depending on the context).

A syntax like `variable : Type` for declarations seems a lot more understandable and consistent for me.

**Comment by asterite** [comment] 2015-11-25 23:46
We will most surely have `variable : Type` (and `@variable : Type`) for type declarations, and a different syntax for the unsafe, uninitialized allocation on the stack.

**Comment by jhass** [comment] 2015-11-25 23:56
Closing this as a duplicate of #758 then.

**Closed by jhass** 2015-11-25 23:56 UTC
Labels: question
