### ISSUE TITLE
Interesting error in type checker in `<expr> if <cond>`

### ISSUE THREAD

**Issue by js-ojus** [manastech/crystal#1448] opened 2015-09-11 13:12 UTC
### Input
```crystal
def foo
  a = [1, 2, 3, 4]
  
  idx = a.index { |el| el == 3 }
  return if !idx
  
  puts a[idx]
end

foo()
```

### Expected
`3`

### Observed
```bash
Error in line 10: instantiating 'foo()'

in line 7: no overload matches 'Array(Int32)#[]' with types (Nil | Int32)
Overloads are:
 - Array(Int32)#[](start : Int, count : Int)
 - Array(Int32)#[](index : Int)
 - Array(Int32)#[](range : Range)
Couldn't find overloads for these types:
 - Array(Int32)#[](Nil)

================================================================================

Nil trace:

  eval:4



  /usr/lib/crystal/enumerable.cr:336

      def index
          ^~~~~

  /usr/lib/crystal/enumerable.cr:340

        nil
        ^
```

### Discussion
Since the `nil` check is already performed, I expected `idx` to be an `Int32` in the line that triggered the error.

Perhaps, `if` not being a block (but a trailing one) caused this?

**Comment by asterite** [comment] 2015-09-11 13:16
This is a duplicate of #1196 . If you use `unless idx` instead of `if !idx` it works fine :-)

**Closed** 2015-09-11 13:19 UTC
Labels: duplicate
