### ISSUE TITLE
Closing Issues

### ISSUE THREAD

**Issue by bararchy** [manastech/crystal#674] opened 2015-05-20 08:02 UTC
@asterite or @jhass  or someone else with authority in here, there are allot of needles opened issues, that have been answered and explained or irrelevant and should be closed.

for example:
#607 
#635 
#589 
#561 

etc... 

This is cluttering and making addressing of actual opened issues quite troublesome.

What do you guys think ?

**Comment by kirbyfan64** [comment] 2015-05-20 16:19
IMO, #607 is kind of an issue...but I'll close it if wanted.

**Comment by asterite** [comment] 2015-05-20 16:46
I don't mind leaving issues open for a while (for a long time). Eventually I close them if we can't reproduce them or if it's an issue for an idea that didn't catch up. #607 is definitely an issue, I just didn't mark it as a bug because I think it's an issue with Travis nor didn't have time to try to reproduce it in a VM.

@bararchy You can use the labels filter, for example to see all bugs.

**Closed** 2015-05-21 11:06 UTC
