### ISSUE TITLE
As ruby, crystal has open class?

### ISSUE THREAD

**Issue by xdougx** [manastech/crystal#1417] opened 2015-09-08 15:14 UTC
Im studying this lang, and I'm wondering the possibility to do something like this:
```crystal
class Foo
end

bar = Foo.new
def bar.bar foo_bar
  puts "this is a '#{foo_bar}'"
end

bar.bar "Foo Bar"
=> this is a 'Foo Bar'
```

is this possible?

**Comment by asterite** [comment] 2015-09-08 15:16
This is a duplicate of #238. You can read/continue the discussion there :-)

**Comment by asterite** [comment] 2015-09-08 15:17
But the short answer is that for now we have no plans to implement this.

**Comment by jhass** [comment] 2015-09-08 15:21
Note the related concept in Ruby is called singleton class. The open class model is what allows

```cr
class Foo
  def foo
  end
end

class Foo
  def bar
  end 
end

**Closed** 2015-09-08 15:20 UTC
Labels: duplicate, question

**Comment by xdougx** [comment] 2015-09-08 15:37
Yeah, I was wondering about this feature because i was studying the Crystal `active_record.cr`, with this feature, work with schema is going to be more clean then define `field` on class as `MongoID` on ruby.
But looking for this feature as I said https://github.com/manastech/crystal/issues/238#issuecomment-138600185, Singleton Class Concept and Open Class is very useful, but i don't know if is viable to sacrifice performance for it.
