### ISSUE TITLE
[RFC] nil conditional operator or try(:ing) too hard

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1431] opened 2015-09-09 22:31 UTC
The current `try` method is long and hard to read, especially with nested try's.  A shorter try operator would make reading conditional code easier. `.?` is one possible name since `?` may be used in a method name it can't be used as a conditional suffix (like C#).

Examples:
`foo.?.bar.baz` would be equivalent to `foo.try &.bar.baz`
`foo.?.bar.?.baz` would be equivalent to `foo.try &.bar.try &.baz`

**Comment by jhass** [comment] 2015-09-09 22:54
Strongly related to, if not a duplicate of #406

**Closed** 2015-09-09 23:08 UTC
Labels: RFC
