### ISSUE TITLE
Request: Crystal Build flag for static compilation

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2101] opened 2016-02-03 19:22 UTC
I can statically link my executables using `LIBRARY_PATH=/opt/crystal/embedded/lib crystal build ...`, but it would be nice to have a command-line flag for this. Also, if any required libraries are absent from the `lib` folder but present elsewhere on the system (e.g. libssl, libcrypto), presumably the compilation will proceed normally but I will end up with a dynamic dependancy on these libraries at runtime? Or will the compilation fail?

Ideally, when compiling with the static flag (that currently does not exist), the compilation would fail if any of the libraries are not available in a static form. Except of course libc.

Static linking can be necessary in certain situations. In fact, I can see pretty much zero use for `Crystal build ...` without it, as the resulting executable _will not run_ on any system lacking the Crystal prereqs, such as the Boehm GC. Given that nobody is likely to have these things, unless they are also writing Crystal code on that machine, essentially a Crystal executable is useless on any system lacking Crystal. In which case, why bother to precompile it at all?

Hooray for static compilation. But having a flag (and failure in the absence of all necessary static libraries) would make this easier.

**Comment by sdogruyol** [comment] 2016-02-03 19:32
:+1: for static compilation.

**Comment by stugol** [comment] 2016-02-03 20:53
FWIW, the following is another way to statically build a crystal program:
```
# crystal build whatever.cr --cross-compile "Linux x86_64" --target "x86_64-unknown-linux-gnu"
# cc whatever.o -o whatever -Wl,-Bstatic -levent -lpcre -lssl -lgc -lcrypto -lz -Wl,-Bdynamic -ldl -lrt -lpthread -lc
```
But it's a bit more hackish than the previous method, and probably less robust.

**Comment by ysbaddaden** [comment] 2016-02-03 20:53
Compiling software with shared libraries is as reasonnable with Crystal than with any other compiled language like C/C++ or D. You're most likely to have to build and create packages for each distribution (and version) you want to support, or have package maintainers do that job.

That being said, static linking is indeed possible, and doesn't require any dedicated flag:
```
$ crystal build --release --link-flags="-static" myapp.cr
```

You'll may have (or want) to specify the directory where to find the embedded `.a` libraries, for example:
```
$ crystal build --release --link-flags="-static -L/opt/crystal/embedded/lib" myapp.cr
```

**Comment by stugol** [comment] 2016-02-03 20:55
@ysbaddaden Nope!
```
opt/crystal/embedded/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x19): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
./.crystal/root/linux-setup.cr/_main.o: In function `~fun_literal_51':
main_module:(.text+0x25c7b): warning: the use of `tempnam' is dangerous, better use `mkstemp'
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
evutil.c:(.text+0x1488): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `evutil_unparse_protoname':
evutil.c:(.text+0xf0d): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_free':
(.text+0x6b): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_ctrl':
(.text+0x284): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_compress_block':
(.text+0x4ca): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_finish':
(.text+0x528): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_init':
(.text+0x659): undefined reference to `deflateInit_'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xaab): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xbcd): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
```

**Comment by ysbaddaden** [comment] 2016-02-03 21:02
@stugol : You'll have to learn about LD and linking in general. Please read the message: You're missing zlib/deflate symbols. You must be missing a static library.

**Comment by stugol** [comment] 2016-02-03 21:13
Oh really?? Then kindly explain why `LIBRARY_PATH=/opt/crystal/embedded/lib crystal build linux-setup.cr` works with no problem!

**Comment by ysbaddaden** [comment] 2016-02-03 21:21
Sigh. Because you have the `.so` installed but not the `.a`? These are usually distributed in dev packages only. Quite logically: they're useless for anything but development.

Static linking works wonderfully for [shards](https://github.com/ysbaddaden/shards) for instance.

**Comment by stugol** [comment] 2016-02-03 21:45
Quite possibly. Although the executable runs perfectly fine on a fresh installation of Debian, so...

Anyhow, this is _precisely_ why I asked for a flag. So I don't end up using dynamic linking by mistake.

**Comment by stugol** [comment] 2016-02-03 21:55
I've put `libz.a` in the directory, yet the code still won't compile. Am I missing another library? And how can I figure out which library it is?

**Comment by luislavena** [comment] 2016-02-04 13:53
@stugol look at the missing functions and the potential existing `.a` files, seems you also need OpenSSL static library too.

**Comment by ysbaddaden** [comment] 2016-02-04 14:23
@stugol did you tell the linker where to find the `libz.a` file? It won't search the current directory, only standard locations (eg: /usr/lib) so you must be explicit. Ie. add `-L.` to the link flags.

I'm closing, since static linking is already possible, and there is nothing a dedicated flag would do better.

**Closed by ysbaddaden** 2016-02-04 14:23 UTC

**Comment by stugol** [comment] 2016-02-04 18:51
I looked at the missing functions, and they all seem to be from `libz.a`, which I have. I also have `libssl.a` and `libcrypto.a`. I added the `-L` flag just like you showed above, but it complains about those missing functions. Do you think you could be slightly more helpful, please, and tell me how to fix this?

**Comment by luislavena** [comment] 2016-02-04 18:56
Please show us the exact command (updated) and the exact output you're
receiving and will try to help you if time allows.

Sorry for top posting, sent from mobile.

**Comment by stugol** [comment] 2016-02-04 19:06
Sure:
```
# crystal build --link-flags="-static -L/opt/crystal/embedded/lib" linux-setup.cr
Using compiled compiler at .build/crystal
/opt/crystal/embedded/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x19): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
evutil.c:(.text+0x1488): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `evutil_unparse_protoname':
evutil.c:(.text+0xf0d): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_free':
(.text+0x6b): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_ctrl':
(.text+0x284): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_compress_block':
(.text+0x4ca): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_finish':
(.text+0x528): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_init':
(.text+0x659): undefined reference to `deflateInit_'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xaab): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xbcd): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "linux-setup" "${@}" -static -L/opt/crystal/embedded/lib -rdynamic  -lz -lssl -lcrypto -levent -lrt -lpcre -lgc -lpthread -ldl`
```
I get the same result if I add `--release`. However, `LIBRARY_PATH=/opt/crystal/embedded/lib crystal build linux-setup.cr` works fine. Also FYI:
```
# ls -l /opt/crystal/embedded/lib
-rw-r--r-- 1 root root   4994 Jan 25 16:14 libatomic_ops.a
-rwxr-xr-x 1 root root    925 Jan 25 16:14 libatomic_ops.la
-rw-r--r-- 1 root root   7932 Jan 25 16:14 libatomic_ops_gpl.a
-rwxr-xr-x 1 root root    937 Jan 25 16:14 libatomic_ops_gpl.la
-rw-r--r-- 1 root root  49714 Jan 25 16:14 libcord.a
-rwxr-xr-x 1 root root   1000 Jan 25 16:14 libcord.la
lrwxrwxrwx 1 root root     37 Feb  3 04:12 libcrypto.a -> /usr/lib/x86_64-linux-gnu/libcrypto.a
lrwxrwxrwx 1 root root     32 Feb  3 21:58 libdl.a -> usr/lib/x86_64-linux-gnu/libdl.a
-rw-r--r-- 1 root root 551880 Jan 25 16:14 libevent.a
-rwxr-xr-x 1 root root    930 Jan 25 16:14 libevent.la
-rw-r--r-- 1 root root 328600 Jan 25 16:14 libevent_core.a
-rwxr-xr-x 1 root root    945 Jan 25 16:14 libevent_core.la
-rw-r--r-- 1 root root 223352 Jan 25 16:14 libevent_extra.a
-rwxr-xr-x 1 root root    948 Jan 25 16:14 libevent_extra.la
-rw-r--r-- 1 root root  25820 Jan 25 16:14 libevent_openssl.a
-rwxr-xr-x 1 root root    969 Jan 25 16:14 libevent_openssl.la
-rw-r--r-- 1 root root   5086 Jan 25 16:14 libevent_pthreads.a
-rwxr-xr-x 1 root root    957 Jan 25 16:14 libevent_pthreads.la
-rw-r--r-- 1 root root 389792 Jan 25 16:14 libgc.a
-rwxr-xr-x 1 root root    959 Jan 25 16:14 libgc.la
-rw-r--r-- 1 root root 286768 Jan 25 16:14 libpcre.a
-rwxr-xr-x 1 root root    902 Jan 25 16:14 libpcre.la
-rw-r--r-- 1 root root  46880 Jan 25 16:14 libpcrecpp.a
-rwxr-xr-x 1 root root    948 Jan 25 16:14 libpcrecpp.la
-rw-r--r-- 1 root root   6494 Jan 25 16:14 libpcreposix.a
-rwxr-xr-x 1 root root    954 Jan 25 16:14 libpcreposix.la
lrwxrwxrwx 1 root root     34 Feb  3 04:11 libssl.a -> /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     18 Jan 25 16:14 libyaml-0.so.2 -> libyaml-0.so.2.0.4
-rwxr-xr-x 1 root root 208679 Jan 25 16:14 libyaml-0.so.2.0.4
-rw-r--r-- 1 root root 248416 Jan 25 16:14 libyaml.a
-rwxr-xr-x 1 root root    984 Jan 25 16:14 libyaml.la
lrwxrwxrwx 1 root root     18 Jan 25 16:14 libyaml.so -> libyaml-0.so.2.0.4
drwxr-xr-x 2 root root   4096 Feb  1 19:50 pkgconfig
```

**Comment by luislavena** [comment] 2016-02-04 19:17
@stugol a couple of things:

- I see no `libz.a` in the directory you're pointing to, so most likely is picking it from somewhere else that has no static version of the library.
- The order of parameters given in `--link-flags` are important.
- The order of the linked libraries is also important

When you're doing `LIBRARY_PATH` prior invoking `crystal`, that is like doing `-L/path` prior `-static` in `--link-flags`

I don't know the contents of your `linux-setup.cr` script, but I've tested locally and static linking works, except the glibc warnings.

You can see the linking command by adding `--verbose` to `crystal build`.

**Comment by stugol** [comment] 2016-02-04 19:25
@luislavena Perhaps your test script wasn't requiring `http/client`? I don't know what happened to the `libz.a` - it was there last time. Maybe I was using a different docker image. Anyhow, I put it there (again) and still get the problem:
```
# ln -s /usr/lib/x86_64-linux-gnu/libz.a /opt/crystal/embedded/lib/
# ls -l /opt/crystal/embedded/lib | grep libz
lrwxrwxrwx 1 root root     32 Feb  4 19:21 libz.a -> /usr/lib/x86_64-linux-gnu/libz.a
# crystal build --verbose --link-flags="-static -L/opt/crystal/embedded/lib" linux-setup.cr
Using compiled compiler at .build/crystal
cc -o "linux-setup" "${@}" -static -L/opt/crystal/embedded/lib -rdynamic  -lz -lssl -lcrypto -levent -lrt -lpcre -lgc -lpthread -ldl
/opt/crystal/embedded/lib/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x19): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
evutil.c:(.text+0x1488): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libevent.a(evutil.o): In function `evutil_unparse_protoname':
evutil.c:(.text+0xf0d): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_free':
(.text+0x6b): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_ctrl':
(.text+0x284): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_compress_block':
(.text+0x4ca): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_finish':
(.text+0x528): undefined reference to `deflateEnd'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `zlib_stateful_init':
(.text+0x659): undefined reference to `deflateInit_'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xaab): undefined reference to `deflate'
/opt/crystal/embedded/lib/libcrypto.a(c_zlib.o): In function `bio_zlib_write':
(.text+0xbcd): undefined reference to `deflateInit_'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "linux-setup" "${@}" -static -L/opt/crystal/embedded/lib -rdynamic  -lz -lssl -lcrypto -levent -lrt -lpcre -lgc -lpthread -ldl`
```
Also `--verbose` doesn't seem to add anything to the output.

**Comment by stugol** [comment] 2016-02-04 19:30
@luislavena You say that setting `LIBRARY_PATH` is like putting `-L` before `-static`, and yet it _does_ result in a statically-linked executable! At least `libcrypto`, `libssl`, the GC and `libevent` get statically linked - I don't know about `libz`.

I know it gets statically linked because the executable will run correctly on a plain Debian installation; whereas it won't if I build it normally.

**Comment by stugol** [comment] 2016-02-04 19:35
@luislavena I've figured out why `libz.a` was missing! I had to delete it to get the `LIBRARY_PATH=` method to compile again. So presumably `libz` depends on something else, that I _also_ need to put in there. **But I don't know what it is!**

**Comment by luislavena** [comment] 2016-02-04 19:35
@stugol sorry, at no point in this issue there was a mention of http/client, except for the one you just did, neither was the source of your script provided, so how it will be possible for me to figure out what is doing?

I just loaded OpenSSL and zlib, and that worked.

Now, to the info you now provide:

```crystal
require "http/client"

response = HTTP::Client.get "https://www.google.com"
puts response.status_code
```

```
$ crystal build --release script.cr -o script-dynamic

$ ldd script-dynamic 
	linux-vdso.so.1 =>  (0x00007ffe65fc9000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f35620d7000)
	libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f3561e6e000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f3561a2b000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f3561823000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f3561605000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f3561400000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f35611e9000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f3560e1f000)
	/lib64/ld-linux-x86-64.so.2 (0x000055a73d6b0000)
```

```
$ crystal build --release script.cr -o script-static --link-flags="-static"
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/bin/../embedded/lib/../lib/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
evutil.c:(.text+0x1486): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/opt/crystal/bin/../embedded/lib/../lib/libevent.a(evutil.o): In function `evutil_unparse_protoname':
evutil.c:(.text+0xf04): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

$ ldd script-static 
	not a dynamic executable
```

I didn't require to play with `LIBRARY_PATH` or even `-L`

> But I don't know what it is!

Me neither, is your machine, your OS and your installation. If something has borked in your end you might need to restore the packages or something.

**Comment by stugol** [comment] 2016-02-04 19:42
@luislavena I realise I had not mentioned `http/client`. I wasn't admonishing you for its omission ;)
```
# ldd linux-setup-dynamic
	linux-vdso.so.1 =>  (0x00007ffef5fcb000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fd03476b000)
	libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fd03450a000)
	libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fd034111000)
	libevent-2.0.so.5 => /usr/lib/x86_64-linux-gnu/libevent-2.0.so.5 (0x00007fd033ec9000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fd033cc1000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fd033a83000)
	libgc.so.1 => /usr/local/lib/libgc.so.1 (0x00007fd03380f000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd0335f3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fd0333ee000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd0331d8000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd032e4d000)
	/lib64/ld-linux-x86-64.so.2 (0x00005606d9df5000)
```
However, this is interesting:
```
# ln -s /usr/lib/x86_64-linux-gnu/libz.a /opt/crystal/embedded/lib/
# ls -l /opt/crystal/embedded/lib/libz.a
lrwxrwxrwx 1 root root 32 Feb  4 19:21 /opt/crystal/embedded/lib/libz.a -> /usr/lib/x86_64-linux-gnu/libz.a
# crystal build --release linux-setup.cr -o linux-setup-static --link-flags="-static"
Using compiled compiler at .build/crystal
/usr/bin/ld: cannot find -lz
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x19): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
(.text+0x116): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.7/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `evutil_getaddrinfo_common':
(.text+0x148f): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "linux-setup-static" "${@}" -static -rdynamic  -lz -lssl -lcrypto -levent -lrt -lpcre -lgc -lpthread -ldl`
```
Why **/usr/bin/ld: cannot find -lz**? It's right there!

**Comment by luislavena** [comment] 2016-02-04 19:48
> Why /usr/bin/ld: cannot find -lz? It's right there!

Once again, is your system and you have stated that you messed with files prior this testing. I recommend you purge and restore the zlib package and development headers/libs in order to continue testing, since remote debugging over a GitHub issue is like trying to assist someone to fix a problem over Twitter, without the 140 characters limit (aka: pointless).

> I wasn't admonishing you for its omission ;)

Perhaps english is not my first language, but there is something in the tone you express your concerns that might indicate otherwise.

But, since we are talking about computers and software, please provide as much details, context and output necessary to reproduce the issue. Perhaps even test on a clean slate/environment before reporting will serve all parties and save everybody's time, not to mention the learning experience.

**Comment by stugol** [comment] 2016-02-04 21:46
Argh. I started afresh on a new system, and now I'm having trouble getting anything to run at all!!
I've done this, as I usually do:
```
apt-get update
apt-get install -y llvm libpcre3-dev build-essential curl git zlib1g-dev automake libtool pkg-config unp libedit-dev libssl-dev libevent-dev libgc-dev libreadline-dev libgdbm-dev
curl http://dist.crystal-lang.org/apt/setup.sh | bash
apt-get install -y crystal
git clone https://github.com/manastech/crystal.git
cd crystal

git clone git://github.com/ivmai/bdwgc.git
cd bdwgc
git clone git://github.com/ivmai/libatomic_ops.git
autoreconf -vif
automake --add-missing
./configure
make
make install

curl -O http://www.xmailserver.org/pcl-1.12.tar.gz
unp pcl-1.12.tar.gz
cd pcl-1.12
./configure
make
make install
cd ../..

rm /usr/lib/libgc.so* || true
apt-get remove libpcl1-dev || true

make
cd ..
ln -s /root/crystal/bin/crystal /usr/local/bin/
ln -s /usr/lib/x86_64-linux-gnu/libcrypto.a /opt/crystal/embedded/lib/
ln -s /usr/lib/x86_64-linux-gnu/libz.a /opt/crystal/embedded/lib/
```
And I'm getting the following error:
```
# crystal eval "puts %{hello}"
Using compiled compiler at .build/crystal
./.crystal/eval/_main.o: In function `__crystal_main':
main_module:(.text+0x5db): undefined reference to `GC_get_push_other_roots'
main_module:(.text+0x641): undefined reference to `GC_set_push_other_roots'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o "/root/.crystal/crystal-run-eval.tmp" "${@}"  -rdynamic  -levent -lrt -lpcre -lgc -lpthread -ldl`
```
I don't understand it! I've done exactly what I always do, and it's not working!

**Comment by stugol** [comment] 2016-02-04 22:18
I added `export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH` and `export LD_LIBRARY_PATH=/usr/local/lib` to my `/etc/bash.bashrc` and that seems to have fixed it.

Also, on this fresh system, it seems to be working:
```
# crystal build --release linux-setup.cr -o linux-setup-static --link-flags="-static"
Using compiled compiler at .build/crystal
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcrypto.a(dso_dlfcn.o): In function `dlfcn_globallookup':
(.text+0x11): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `test_for_getaddrinfo_hacks':
(.text+0x154): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libevent.a(evutil.o): In function `evutil_getaddrinfo_common':
(.text+0x1761): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
# ldd linux-setup-static
	not a dynamic executable
```
Does this message mean that _all_ libraries have been linked statically? Isn't it a bad idea to statically link `libc`?

Thanks for the help.

**Comment by kirbyfan64** [comment] 2016-02-04 22:19
The message just means that there's still a dependency on shared libc.

**Comment by stugol** [comment] 2016-02-04 22:20
No, I mean `not a dynamic executable`

**Comment by luislavena** [comment] 2016-02-04 22:30
> Does this message mean that all libraries have been linked statically? Isn't it a bad idea to statically link libc?

Yes, is a bad idea, and that is why gives you a warning that `glibc` will be loaded at execution time instead, so it will depend on the platform you compiled to run against it.

In order not to depend of the platform glibc, you might search for musl libc implementation (there are open issues about this, but the level of knowledge is high, be warned).

**Comment by stugol** [comment] 2016-02-04 22:31
Is there some way to dynamically link `libc` whilst statically linking everything else? Or doesn't it matter?

**Comment by luislavena** [comment] 2016-02-04 22:33
@stugol learn about linking options, like `-Wl,Bdynamic` and `-Wl,Bstatic`, you can play with those options to decide which libraries will be statically and which libraries will be linked dynamically or statically.

**Comment by stugol** [comment] 2016-02-04 22:37
I know about those. But there's no way to inject them into the Crystal build process is there, except by doing a two-stage build using the `--cross-compile` flag.

**Comment by ShalokShalom** [comment] 2017-08-29 09:11
Is this solved?

**Comment by RX14** [comment] 2017-08-29 12:20
Yes, but this issue is already closed. See #4872.
