### ISSUE TITLE
support File.realpath , thanks .

### ISSUE THREAD

**Issue by sevk** [manastech/crystal#1996] opened 2016-01-06 08:13 UTC
```ruby

#auto make link to /dev/sdb1
# /mnt/U -> /dev/sdb1

$fnBK = "/mnt/U" #USB DISK

def mkln(s)
  `sudo ln -s #{s } #{$fnBK} -f ` if s != ""
  puts "mk ln OK"
end

s=`df -h | grep /dev/sd[b-z]1 | grep -o "/mnt.*" `.strip
if File.exists? $fnBK
  if File.realpath($fnBK ) != s
    puts `sudo rm #{$fnBK} `
    mkln s
  else
    puts "OK"
  end
else
  mkln s
end
                                                                
```

```C

▶ pry
[1] pry(main)> show-source File.realpath

From: file.c (C Method):
Owner: #<Class:File>
Visibility: public
Number of lines: 7

static VALUE
rb_file_s_realpath(int argc, VALUE *argv, VALUE klass)
{
    VALUE path, basedir;
    rb_scan_args(argc, argv, "11", &path, &basedir);
    return rb_realpath_internal(basedir, path, 1);
}


```

**Comment by asterite** [comment] 2016-01-06 14:39
Duplicate of #1519

**Closed by asterite** 2016-01-06 14:39 UTC
