### ISSUE TITLE
Unintuitive type failure with hashes and tuples.

### ISSUE THREAD

**Issue by yxhuvud** [manastech/crystal#1769] opened 2015-10-18 11:53 UTC
```cr
alias GrammarSymbol = Symbol | Char
alias Tag = GrammarSymbol

foo = {} of {Tag, Int32} => Int32

"test".each_char do |char|
  foo[{char, 42}] = 42
end

puts x[{'a', 5}]

```
Gives
```
"test".each_char do |char|
       ^~~~~~~~~

in ./test.cr:13: no overload matches 'Hash({Char | Symbol, Int32}, Item)#[]=' with types {Char, Int32}, Item
Overloads are:
 - Hash({Char | Symbol, Int32}, Item)#[]=(key : {Char | Symbol, Int32}, value : Item)

  foo[{char, 42}] = Item.new "foo"

**Comment by asterite** [comment] 2015-10-18 13:25
Duplicate of #357. Use a `record`.

**Closed by asterite** 2015-10-18 13:25 UTC
Labels: bug, compiler
