### ISSUE TITLE
Bug: `@bar` at expanded macro: getter:5:9 has no type

### ISSUE THREAD

**Issue by netfeed** [manastech/crystal#1261] opened 2015-08-22 22:53 UTC
Tried to do this to define a singelton:

```crystal
class Foo
  @@test = new

  def self.singelton
    return @@test
  end

  getter :bar

  def initialize
    @bar = "foo"
  end
end

fb  = Foo.singelton
puts fb.bar
```

And got this error:

```
Bug: `@bar` at expanded macro: getter:5:9 has no type
*raise<String>:NoReturn +58 [0]
*Crystal::InstanceVar@Crystal::ASTNode#type<Crystal::InstanceVar>:Crystal::Type+ +321 [0]
*Crystal::CodeGenVisitor#read_instance_var<Crystal::CodeGenVisitor, Crystal::InstanceVar, Crystal::Type+, String, LLVM::Value>:Bool +201 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +7610 [0]
*Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1755 [0]
*Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +1827 [0]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +2195 [0]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1016 [0]
*Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Int32 | Bool) +3261 [0]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4852 [0]
*Crystal::Command::run_command<Array(String)>:Nil +140 [0]
*Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +100 [0]
main +17164 [0]
__libc_start_main +245 [0]
_start +41 [0]

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues
```

The code itself probably doesn't work properly, but error seems important.

**Comment by bcardiff** [comment] 2015-08-23 00:36
FYI. If you move the `@@test = new` to the bottom of the class it works.
Also, you can use `getter bar` instead of `getter :bar`

```crystal
class Foo
  def self.singelton
    return @@test
  end

  getter bar

  def initialize
    @bar = "foo"
  end

  @@test = new
end

fb = Foo.singelton
puts fb.bar # => foo
```

**Comment by netfeed** [comment] 2015-08-23 06:20
Oh, nice, so that works. I pasted the wrong version of the error too, the one above is with getter, this is with "def bar":

```
Bug: `@bar` at /home/netfeed/cpp/test.cr:9:5 has no type
*raise<String>:NoReturn +58 [257]
*Crystal::InstanceVar@Crystal::ASTNode#type<Crystal::InstanceVar>:Crystal::Type+ +321 [257]
*Crystal::CodeGenVisitor#read_instance_var<Crystal::CodeGenVisitor, Crystal::InstanceVar, Crystal::Type+, String, LLVM::Value>:Bool +201 [257]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +7610 [257]
*Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1755 [257]
*Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +1827 [257]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +2195 [257]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1016 [257]
*Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Int32 | Bool) +3261 [257]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4852 [257]
*Crystal::Command::run_command<Array(String)>:Nil +140 [257]
*Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +100 [257]
main +17164 [257]
__libc_start_main +245 [257]
_start +41 [257]

Error: you've found a bug in the Crystal compiler. Please open an issue, including source code that will allow us to reproduce the bug: https://github.com/manastech/crystal/issues
```

**Comment by asterite** [comment] 2015-08-23 22:48
This is actually a duplicate of #718. We'll fix it when we split the two type inference phase into three phases.

**Closed by asterite** 2015-08-23 22:48 UTC
Labels: duplicate
