### ISSUE TITLE
Crystal installation failing on travis.

### ISSUE THREAD

**Issue by vjdhama** [manastech/crystal#2012] opened 2016-01-14 05:42 UTC
Suddenly builds started to fail because of failing crystal installation on Travis. 

Relevant Logs

```
Installing Crystal
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /tmp/tmp.4f8XoP5XRu --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d//apt.postgresql.org.gpg --keyserver keys.gnupg.net --recv-keys 09617FD37CC06B54
gpg: requesting key 7CC06B54 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Success
gpg: no valid OpenPGP data found.

WARNING: The following packages cannot be authenticated!
  crystal
E: There are problems and -y was used without --force-yes
Installing Shards

$ crystal --version
/home/travis/build.sh: line 45: crystal: command not found
$ crystal deps --version
/home/travis/build.sh: line 45: crystal: command not found

$ crystal deps
/home/travis/build.sh: line 45: crystal: command not found

```

More [here](https://api.travis-ci.org/jobs/102272527/log.txt?deansi=true).

**Comment by sdogruyol** [comment] 2016-01-14 08:09
I can confirm the same

**Comment by jhass** [comment] 2016-01-14 08:12
Closing as a duplicate of https://github.com/travis-ci/travis-ci/issues/5461

**Closed by jhass** 2016-01-14 08:12 UTC
