### ISSUE TITLE
Exception handling syntax is not Ruby compliant

### ISSUE THREAD

**Issue by lepieru** [manastech/crystal#1732] opened 2015-10-13 15:54 UTC
The Crystal rescue syntax is not Ruby compliant. With exception handling, Crystal failed to run Ruby code, and vice versa.

In Crystal, it looks like :

```ruby
rescue e : TypeOfException
```

But in Ruby, we can see :

```ruby
rescue TypeOfExcepion => e
```

I think it is weird to choose not to follow the Ruby syntax on this kind of detail. Would someone kindly put me in the picture ?

Seriously, this is not about the best syntax, I just complain about this unexpected incompatibility.

**Comment by asterite** [comment] 2015-10-13 16:40
1. Crystal is not a Ruby implementation, there are many syntax differences
2. `=>` is used in Ruby for hash literal. In crystal we use `:` for type restrictions, so we think `:` is more consistent. We think `=>` in exception syntax in Ruby is inconsistent.

**Comment by lepieru** [comment] 2015-10-13 21:35
I understand the compiled program problematics. Crystal cannot handle the dynamical properties of a Ruby VM. Moreover, **Crystal typing syntax is needed** and Ruby interpreters yell on parsing. However, it is thinkable to have compatible parsers in both world. Rubies could update their parser to ignore typing syntax ([Python 3.5 seems to behave like this](https://docs.python.org/3.5/library/typing.html)).

We don't have the option to write Ruby-Crystal friendly code today (this is the case for exceptions handling). I just notice that **some maybe justified but avoidable things** don't follow the way to make it possible.

**Comment by asterite** [comment] 2015-10-13 21:39
I'll close this because it's starting to look like a duplicate of https://github.com/manastech/crystal/issues/593

We have no plans of changing Crystal's syntax to make it Ruby compatible.

**Closed by asterite** 2015-10-13 21:39 UTC
Labels: question
