### ISSUE TITLE
abstract method implementation isn't enforced in non-abstract subclasses

### ISSUE THREAD

**Issue by jreinert** [manastech/crystal#1644] opened 2015-09-29 16:43 UTC
``` crystal
abstract class Foo
  abstract def foo : Int32
end

class Bar < Foo
  def foo
    "foo"
  end
end

class Foobar < Foo
  def fooo
    3
  end
end
```

**Comment by jhass** [comment] 2015-09-29 16:46
Duplicate of #835

**Closed by jhass** 2015-09-29 16:46 UTC
