### ISSUE TITLE
Compiler crash trying out moonshine library

### ISSUE THREAD

**Issue by bebac** [manastech/crystal#1133] opened 2015-08-09 08:05 UTC
Projectfile:

    deps do
        github "dhruvrajvanshi/Moonshine", name: "moonshine" 
    end

App:
  
    require "./moonshine_app/*"
    require "moonshine/moonshine"

    include Moonshine
    include Moonshine::Utils::Shortcuts
    include Moonshine::Base

    app = App.new

    # respond to all HTTP verbs
    app.route "/", do |request|
        ok("Hello Moonshine!")
    end

    # or particular HTTP verbs
    app.get "/get", do |request|
        ok("This is a get response")
    end

    # you can set response headers
    app.get "api", do |request|
        res = ok("{ name : 'moonshine'}")
        res.headers["Content-type"] = "text/json"
        res
    end

    app.run(8000)

crystal build src/moonshine_app.cp:

    ; ModuleID = 'main_module'

    %String = type { i32, i32, i32, i8 }
    %"Array(Int32)" = type { i32, i32, i32, i32* }
    %Nil = type {}
    %Fiber = type { i32, i8*, %"(( -> Nil) | ( -> Void))", i8*, i8*, i8*, %Fiber*, %Fiber* }
    %"(( -> Nil) | ( -> Void))" = type { i32, [2 x i64] }
    %"Moonshine::Base::App" = type { i32, %"Array(String)"*, %"Hash(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"*, %"Hash(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"*, %"Array((Moonshine::Http::Request -> Moonshine::Http::MiddlewareResponse))"*, %"Array((Moonshine::Http::Request, Moonshine::Http::Response -> Moonshine::Http::Response))"*, %"Array(Moonshine::Middleware::Base+)"*, %"Array(Moonshine::Base::Controller+)"* }
    %"Array(String)" = type { i32, i32, i32, %String** }
    %"Hash(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))" = type { i32, i32, %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"**, i32, i32, %Nil, %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"*, %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"* }
    %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))" = type { i32, %"Moonshine::Base::Route"*, %"->", %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"*, %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"*, %"Hash(K, V)::Entry(Moonshine::Base::Route, ((Moonshine::Http::Request -> Moonshine::Http::Response) | Moonshine::Base::Controller+))"* }
    %"Moonshine::Base::Route" = type { i32, %String*, %String* }
    %"->" = type { i8*, i8* }
    %"Hash(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))" = type { i32, i32, %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"**, i32, i32, %Nil, %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"*, %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"* }
    %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))" = type { i32, i32, %"->", %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"*, %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"*, %"Hash(K, V)::Entry(Int32, (Moonshine::Http::Request -> Moonshine::Http::Response))"* }
    %"Array((Moonshine::Http::Request -> Moonshine::Http::MiddlewareResponse))" = type { i32, i32, i32, %"->"* }
    %"Array((Moonshine::Http::Request, Moonshine::Http::Response -> Moonshine::Http::Response))" = type { i32, i32, i32, %"->"* }
    %"Array(Moonshine::Middleware::Base+)" = type { i32, i32, i32, i32** }
    %"Array(Moonshine::Base::Controller+)" = type { i32, i32, i32, i32** }
    %"struct.LibABI::UnwindException" = type { i64, i64, i64, i64, i64, i32 }

    @"'finalize'" = private constant { i32, i32, i32, [9 x i8] } { i32 1, i32 8, i32 8, [9 x i8] c"finalize\00" }
    @"'server'" = private constant { i32, i32, i32, [7 x i8] } { i32 1, i32 6, i32 6, [7 x i8] c"server\00" }
    @"'call'" = private constant { i32, i32, i32, [5 x i8] } { i32 1, i32 4, i32 4, [5 x i8] c"call\00" }
    @":symbol_table" = global [3 x %String*] [%String* bitcast ({ i32, i32, i32, [9 x i8] }* @"'finalize'" to %String*), %String* bitcast ({ i32, i32, i32, [7 x i8] }* @"'server'" to %String*), %String* bitcast ({ i32, i32, i32, [5 x i8] }* @"'call'" to %String*)]
    @"LibC::PROT_READ" = constant i32 1
    @"LibC::PROT_WRITE" = constant i32 2
    @"LibC::MAP_PRIVATE" = constant i32 2
    @"LibC::MAP_ANON" = constant i32 32
    @"'unwind'" = private constant { i32, i32, i32, [7 x i8] } { i32 1, i32 6, i32 6, [7 x i8] c"unwind\00" }
    @"Unwind::REG_IP" = constant i32 -1
    @"'pthread'" = private constant { i32, i32, i32, [8 x i8] } { i32 1, i32 7, i32 7, [8 x i8] c"pthread\00" }
    @"'gc'" = private constant { i32, i32, i32, [3 x i8] } { i32 1, i32 2, i32 2, [3 x i8] c"gc\00" }
    @"Int::DIGITS_DOWNCASE" = constant %String* bitcast ({ i32, i32, i32, [37 x i8] }* @"'0123456789abcdefghi...'" to %String*)
    @"'0123456789abcdefghi...'" = private constant { i32, i32, i32, [37 x i8] } { i32 1, i32 36, i32 36, [37 x i8] c"0123456789abcdefghijklmnopqrstuvwxyz\00" }
    @"Int::DIGITS_UPCASE" = constant %String* bitcast ({ i32, i32, i32, [37 x i8] }* @"'0123456789ABCDEFGHI...'" to %String*)
    @"'0123456789ABCDEFGHI...'" = private constant { i32, i32, i32, [37 x i8] } { i32 1, i32 36, i32 36, [37 x i8] c"0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ\00" }
    @"String::TYPE_ID" = constant i32 1
    @"String::HEADER_SIZE" = constant i32 trunc (i64 mul nuw (i64 ptrtoint (i32* getelementptr (i32* null, i32 1) to i64), i64 3) to i32)
    @"String::CHAR_TO_DIGIT" = global [256 x i8] undef
    @"Time::TicksMask" = constant i64 4611686018427387903
    @"Time::MAX_VALUE_TICKS" = constant i64 3155378975999999999
    @"Time::DAYS_MONTH" = external global %"Array(Int32)"*

    define internal %Nil @__crystal_main(i32 %argc, i8** %argv) {
    alloca:
      %__temp_85 = alloca %Fiber*
      %app = alloca %"Moonshine::Base::App"*
      %table = alloca [256 x i8]
      %0 = alloca [256 x i8]
      %i = alloca i8
      %i1 = alloca i8
      %i2 = alloca i8
      %i3 = alloca i8
      %__temp_167 = alloca %"Array(Int32)"*
      %__temp_168 = alloca i32*

    entry:                                            ; No predecessors!
      %1 = call [256 x i8] @"*StaticArray(Int8, 256)::new<StaticArray(Int8, 256):Class, Int8>:StaticArray(Int8, 256)"(i32 623, i8 -1)
      store [256 x i8] %1, [256 x i8]* %0
      %2 = load [256 x i8]* %0
      store [256 x i8] %2, [256 x i8]* %table
      store i8 0, i8* %i1
      br label %while

    while:                                            ; preds = %body, %entry
      %3 = load i8* %i1
      %4 = icmp slt i8 %3, 10
      br i1 %4, label %body, label %exit

    body:                                             ; preds = %while
      %5 = load i8* %i1
      store i8 %5, i8* %i
      %6 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
      %7 = load i8* %i
      %8 = sext i8 %7 to i32
      %9 = add i32 48, %8
      %10 = load i8* %i
      %11 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %6, i32 %9, i8 %10)
      %12 = load i8* %i1
      %13 = sext i8 %12 to i32
      %14 = add i32 %13, 1
      %15 = trunc i32 %14 to i8
      store i8 %15, i8* %i1
      br label %while

    exit:                                             ; preds = %while
      store i8 0, i8* %i3
      br label %while4

    while4:                                           ; preds = %body5, %exit
      %16 = load i8* %i3
      %17 = icmp slt i8 %16, 26
      br i1 %17, label %body5, label %exit6

    body5:                                            ; preds = %while4
      %18 = load i8* %i3
      store i8 %18, i8* %i2
      %19 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
      %20 = load i8* %i2
      %21 = sext i8 %20 to i32
      %22 = add i32 65, %21
      %23 = load i8* %i2
      %24 = sext i8 %23 to i32
      %25 = add i32 %24, 10
      %26 = trunc i32 %25 to i8
      %27 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %19, i32 %22, i8 %26)
      %28 = call i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]* %table)
      %29 = load i8* %i2
      %30 = sext i8 %29 to i32
      %31 = add i32 97, %30
      %32 = load i8* %i2
      %33 = sext i8 %32 to i32
      %34 = add i32 %33, 10
      %35 = trunc i32 %34 to i8
      %36 = call i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8* %28, i32 %31, i8 %35)
      %37 = load i8* %i3
      %38 = sext i8 %37 to i32
      %39 = add i32 %38, 1
      %40 = trunc i32 %39 to i8
      store i8 %40, i8* %i3
      br label %while4

    exit6:                                            ; preds = %while4
      %41 = load [256 x i8]* %table
      store [256 x i8] %41, [256 x i8]* @"String::CHAR_TO_DIGIT"
    }

    declare i32 @printf(i8*, ...)

    declare i8* @__crystal_malloc(i32)

    declare i8* @__crystal_realloc(i8*, i32)

    ; Function Attrs: noreturn
    declare void @__crystal_raise(%"struct.LibABI::UnwindException"*) #0

    declare i8* @__crystal_malloc_atomic(i32)

    declare [256 x i8] @"*StaticArray(Int8, 256)::new<StaticArray(Int8, 256):Class, Int8>:StaticArray(Int8, 256)"(i32, i8)

    declare i8* @"*StaticArray(Int8, 256)@StaticArray(T, N)#to_unsafe<StaticArray(Int8, 256)>:Pointer(Int8)"([256 x i8]*)

    declare i8 @"*Pointer(Int8)@Pointer(T)#[]=<Pointer(Int8), Int32, Int8>:Int8"(i8*, i32, i8)

    attributes #0 = { noreturn }
    Bug: [0, 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31] at /opt/crystal/src/time/time.cr:36:16 should have been expanded
    *raise<String>:NoReturn +70 [0]
    *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +25037 [0]
    *Crystal::CodeGenVisitor#initialize_const<Crystal::CodeGenVisitor, Crystal::Const, String>:(Nil | LLVM::Value) +737 [0]
    *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:(Nil | Bool) +534 [0]
    *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2554 [0]
    *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1421 [0]
    *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2787 [0]
    *Crystal::Program#build<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +187 [0]
    *Crystal::Compiler#build<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Int32 | Bool) +3466 [0]
    *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +5123 [0]
    *Crystal::Command::run<Array(String)>:(Nil | Bool | FileDescriptorIO+ | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +1853 [0]
    main +17469 [0]
    __libc_start_main +240 [0]
    _start +41 [0]

    Error: you've found a bug in the Crystal compiler. Please open an issue: https://github.com/manastech/crystal/issues

**Comment by bebac** [comment] 2015-08-09 08:09
Version:

    Crystal 0.7.5 [2a33a87] (Thu Jul 30 17:32:32 UTC 2015)

**Comment by jhass** [comment] 2015-08-09 09:19
can you also post your  `.deps.lock` please? In case moonshine (accidentally) works around it.

**Comment by bebac** [comment] 2015-08-09 09:27
.deps.lock looks like this:

    {
      "moonshine": "4ae23d4fd1de824dd5c10a8d1478c37f57e56f83"
    }

**Comment by bebac** [comment] 2015-08-09 09:30
Note that the name arguments doesn't matter. It also happens if you leave out the name and just do require "Moonshine/moonshine"

**Comment by asterite** [comment] 2015-08-10 00:28
This is a duplicate of #1028, if you try it with the new compiler it works OK.

**Closed by asterite** 2015-08-10 00:28 UTC
Labels: bug
