### ISSUE TITLE
if var doesn't remove nil from type inference

### ISSUE THREAD

**Issue by elthariel** [manastech/crystal#1957] opened 2015-12-17 08:52 UTC
According to documentation and if I understand correctly, using a `if var` is supposed to restrict the type in the if branch. This isn't working on the latest crystal build. Here's a sample code to reproduce

```crystal
class Test
  @callback = nil

  def on_callback(&block)
    @callback = block
  end

  def call
    if @callback
      @callback.call
    end
  end
end

test = Test.new
test.on_callback { puts "Called !" }
test.call
```

Running the previous code yields the following output:
```
Error in /tmp/test.cr:17: instantiating 'Test#call()'

test.call
     ^~~~

in /tmp/test.cr:10: undefined method 'call' for Nil (compile-time type is (( -> Void))?)

      @callback.call
                ^~~~

================================================================================

Nil trace:

  /tmp/test.cr:2

      @callback = nil
      ^

  /tmp/test.cr:2

      @callback = nil
                  ^
```

Is this the intended behavior ? If so, what's the correct implementation ?
If this is a bug, my crystal compiler and llvm knowledge is nil but I'm willing to have a look if you give me some pointers in the codebase

**Comment by elthariel** [comment] 2015-12-17 09:08
Damn, i can't bisect this :-/

**Comment by jhass** [comment] 2015-12-17 09:28
Closing as a duplicate of #477. Assign it to a local variable first.

**Closed by jhass** 2015-12-17 09:28 UTC
Labels: question

**Comment by elthariel** [comment] 2015-12-17 09:59
Thanks @jhass. I was sure there were similar bugs but i wasn't able to find them
