### ISSUE TITLE
Script doesn't accept arguments

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2087] opened 2016-01-30 23:20 UTC
When running a script, command-line arguments are interpreted as additional filenames, rather than arguments; even if the script was run directly, using a shebang line:
```
#!/usr/bin/env crystal
puts ARGV
```
```
> ./test.cr hello
Error: File hello does not exist
```
This is unhelpful. By all means require the `--` separator when invoking a script via the `crystal` binary (`crystal test.cr -- hello`) but when running the script directly this is just silly and wrong.

**Comment by asterite** [comment] 2016-01-31 00:24
Duplicate of #2087. I still don't know what's the best solution for this.

**Closed by asterite** 2016-01-31 00:24 UTC

**Comment by stugol** [comment] 2016-01-31 00:30
What, this is a duplicate of itself?

**Comment by asterite** [comment] 2016-01-31 00:32
LOL, bad copy/paste, of #546
