### ISSUE TITLE
Why does Hash not have a inject/reduce/fold method?

### ISSUE THREAD

**Issue by benjreinhart** [manastech/crystal#798] opened 2015-06-15 04:08 UTC
Sorry if the answer to this question is documented somewhere, but why is there no `inject` method on `Hash`? `Array` has `inject` via `Enumerable`.

I see that I can open hash up and add it, but I'm curious as to why this isn't in the standard lib?

```crystal
class Hash(K, V)
  def inject(memo)
    each do |k, v|
      memo = yield memo, {k, v}
    end
    memo
  end
end
```

Also, why does `Hash` not include `Enumerable` like in Ruby?

**Comment by asterite** [comment] 2015-06-17 14:03
Hi @benjreinhart,

It's because `Hash` is not `Enumerable` in Crystal.

The main limitation right now is that Ruby autoexpands multiple yield values. `Hash#each` yields two things, a key and a value, but our `Enumerable` only expects one value.

For now you can do this:

```crystal
h = {1 => 2, 3 => 4}
result = h.each.inject(10) do |memo, key_and_value|
  memo + key_and_value[0] + key_and_value[1]
end
p result
```

By invoking `Hash#each` you get an [Iterator](http://crystal-lang.org/api/index.html#http%3A//crystal-lang.org/api/Iterator.html). `Iterator` does have `inject` because it's also Enumerable, but here the Iterator is of a tuple. That's why you have to do `key_and_value[0]`, etc.

I'll mark this as a duplicate of #105 because it's basically the same feature that we need (if we ever decide to do it).

**Closed** 2015-06-17 14:05 UTC
Labels: duplicate, question
