### ISSUE TITLE
Build a shared library (.so)

### ISSUE THREAD

**Issue by boghison** [manastech/crystal#1141] opened 2015-08-10 16:31 UTC
Is this possible?

**Comment by jhass** [comment] 2015-08-10 16:52
There's a sort of PoC at https://gist.github.com/k2b6s9j/3bd3aadd71db206e828f but there's no real support for it, no.

**Comment by jhass** [comment] 2015-08-18 08:26
Duplicate of #921

**Closed** 2015-08-18 13:09 UTC
