### ISSUE TITLE
possible Enumerable/Iterable .map bug

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1199] opened 2015-08-16 23:57 UTC
When map is used the expected Enumerable type is incorrect.  The bug seems to appear with any tuple types.

```
class A
# why doesn't this work?
  include Enumerable({Int32, String})

# but this does???
#  include Enumerable(Int32)

  def each
    yield 1, "foo"
    yield 3, "bar"
  end
end

a = A.new
a.each do |k, v|
  puts "#{k} #{v} #{typeof(k)} "
end
p a.map { |k, v| "foo" }
```

The same code also failed with Iterable/Iterator.
http://carc.in/#/r/bkv

**Comment by asterite** [comment] 2015-08-18 22:57
It's because yielding multiple values doesn't mean yielding a tuple of those values. I don't consider this a bug. 

Also check this: https://github.com/manastech/crystal/issues/105#issuecomment-131547103

So I think this is a duplicate of #105, but please reopen if not

**Closed by asterite** 2015-08-18 22:57 UTC

**Comment by waterlink** [comment] 2015-08-18 23:09
BTW, Working version of provided code example: http://carc.in/#/r/bww

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-08-19 0:58 GMT+02:00 Ary Borenszweig <notifications@github.com>:

**Comment by jhass** [comment] 2015-08-18 23:11
Instead of `Tuple.new(1, "foo")` you can just write `{1, "foo"}` though.

**Comment by alex-fedorov** [comment] 2015-08-18 23:19
@jhass yeah: http://carc.in/#/r/bwx Though parenthesis for `yield` are required in this case (so that parser does not confuse it with block)

**Comment by technorama** [comment] 2015-08-19 06:41
I would like yield(a, b) to work with Enumerable AND map { |a, b| }.
No solution provided works so far.

This issue similar but not identical to #105.  The issue here is with Enumerable and the types that it accepts.  I would like yield(a, b) to work with Enumerable AND map { |a, b| }.

1. yield(a, b) is not a tuple
2. yield({a, b}) yields a single tuple to a block in map

* include Enumerable({a, b}) works, but map { |a, b| } doesn't work
* include Enumerable(a, b) is not possible

Possible solutions:
* Make Enumerable(a, b) work with multiple values (non-tuple)
* Make yield(a, b) a tuple and automatically destructure in the block
* Other?

**Comment by technorama** [comment] 2015-08-19 06:45
I would like yield(a, b) to work with Enumerable AND map { |a, b| }.
No solution provided works so far.

This issue similar but not identical to #105.  The issue here is with Enumerable and the types that it accepts.  I would like yield(a, b) to work with Enumerable AND map { |a, b| }.

1. yield(a, b) is not a tuple
2. yield({a, b}) yields a single tuple to a block in map

* include Enumerable({a, b}) works, but map { |a, b| } doesn't work
* include Enumerable(a, b) is not possible

Possible solutions:
* Make Enumerable(a, b) work with multiple values (non-tuple)
* Make yield(a, b) a tuple and automatically destructure in the block
* Other?
