### ISSUE TITLE
C Function Requires Param Names

### ISSUE THREAD

**Issue by weskinner** [manastech/crystal#426] opened 2015-02-18 17:15 UTC
```
lib MyLib
  fun cfun(Void*, Void* ->) 
end

MyLib.cfun(x, ->(val : Void*) {}) 
```
gives
```
Error in ./wrong_args.cr:5: wrong number of arguments for 'MyLib#cfun' (2 for 1)

MyLib.cfun(x, ->(val : Void*) {})
```

however, builds fine when I name the parameters to cfun

**Comment by asterite** [comment] 2015-02-18 17:21
Yes, this is something that we might want to change/fix. The problem is that this is a valid type:

```crystal
Int32, String -> Char
```

That's a function taking an int and a string and returning a char. So, when the compiler sees this:

```crystal
fun cfun(Void*, Void* ->) 
```

It thinks that's a single argument: a function receiving two void pointers and returning void.

It works if you put parenthesis around the first type:

```crystal
fun cfun((Void*), Void* ->) 
```

Or around the second:

```crystal
fun cfun(Void*, (Void* ->))
```

This can, indeed, be confusing. So for function types we might want to always require parenthesis. But I think that will make things more verbose:

```crystal
alias F = (Int32 -> Int32)

def foo(&block : (Int32 -> Int32))
end
```

(although we might drop the requirement of parenthesis for the block argument).

Anyway... grammar conflicts :-)

**Comment by jhass** [comment] 2015-02-18 17:32
How about allowing to redefine `_` as a compromise (not necessarily only for C functions in fact).

```ruby
fun cfun(_ : Void*, _ : Void*, _ : Void* ->)

**Comment by weskinner** [comment] 2015-02-18 17:39
ahh that makes sense.  The `fun cfun(Void*, (Void* ->))` version seems clearest.

**Comment by asterite** [comment] 2015-06-16 18:17
You can also do:

```crystal
lib MyLib
  fun cfun((Int32), (Int64))
end

MyLib.cfun(1, 1_i64)
``

That is, surround each argument type with parenthesis to avoid the ambiguity. This works right now so there's no need for other alternatives, I think, so I'll close this.

**Closed by asterite** 2015-06-16 18:17 UTC
