### ISSUE TITLE
Generic constraints?

### ISSUE THREAD

**Issue by azazeal** [manastech/crystal#1774] opened 2015-10-18 17:39 UTC
Hey, the docs aren't really clear on this but how can someone declare constraints on generic classes?

Take a look at the following example:

```crystal
abstract class Context
  abstract def bootstrap : Void
end

class App(C) # C should only allow for sub-classes of Context
end
```

Furthermore, the single letter (plus maybe one digit) naming rule for type variables seems a bit restrictive.

Any ideas on this?

**Comment by jhass** [comment] 2015-10-18 18:44
Duplicate of #934

**Closed by jhass** 2015-10-18 18:44 UTC
