### ISSUE TITLE
JNI

### ISSUE THREAD

**Issue by k2b6s9j** [manastech/crystal#508] opened 2015-04-02 06:02 UTC
I'm not entirely sure where to ask this, so I'm sorry if I am the wrong location. I was wondering how I would go about working with Java in Crystal. I want to create a Java source file and use Crystal to write the implementation. I have a basic understanding of how to do this with C and C++, but I'm unsure how to do this with Crystal.

**Comment by jhass** [comment] 2015-04-02 10:35
Never looked into it but afaik the JVM exposes a C API. You would write a binding to this API and use it, see http://crystal-lang.org/docs/syntax_and_semantics/c_bindings/README.html

**Comment by asterite** [comment] 2015-04-02 16:00
Hi,

I don't think Crystal is meant to be used like this, specially because it has its own GC. That means your Java program will end up with two different GCs (unless there's a way to hook into the JVM's GC).

Anyway, it's possible. Try this:

```java
// HelloJNI.java

public class HelloJNI {
   static {
      System.loadLibrary("hello"); // Load native library at runtime
                                   // hello.dll (Windows) or libhello.so (Unixes) or libhello.jnilib (Mac)
   }

   // Declare a native method sayHello() that receives nothing and returns void
   private native void sayHello();

   // Test Driver
   public static void main(String[] args) {
      new HelloJNI().sayHello();  // invoke the native method
   }
}
```

```crystal
# hello.cr

# fun and def in crystal must start with lowercase letter, but we can use
# an alias so we can define them with uppercase letters (needed by JNI)
# Also, I just used Void* but you would need to write proper bindings to use
# the types from Java, like jenv and jobject.
fun hello = Java_HelloJNI_sayHello(env : Void*, obj : Void*) : Void
  # We need to initialize the GC
  GC.init

  # We need to invoke Crystal's "main" function, the one that initializes
  # all constants and runs the top-level code (none in this case, but without
  # constants like STDOUT and others the last line will crash).
  # We pass 0 and null to argc and argv.
  LibCrystalMain.__crystal_main(0, Pointer(Pointer(UInt8)).null)

  a = [1, 2, 3].map { |x| x + 1 }

  puts "Hello! A is #{a}"
end
```

Then compile the Java program:

```
javac HelloJNI.java 
```

Compile the Crystal program to a .jnilib, .so or .dll (I'm on a Mac, so I'm using jnilib):

```
crystal hello.cr --link-flags "-dynamiclib" -o libhello.jnilib
``` 

And then run the Java program:

```
java -Djava.library.path=. HelloJNI
```

(Without the library path it seems to work too, but just in case...)

The output I get is:

```
Hello! A is [2, 3, 4]
```

Well, there you go :-)

I followed these tutorials: http://mrjoelkemp.com/2012/01/getting-started-with-jni-and-c-on-osx-lion/ and https://www3.ntu.edu.sg/home/ehchua/programming/java/JavaNativeInterface.html . When I wrote the JNI stuff in C/C++ the generated function by LLVM had some attributes like "sp" and "uwtable", I don't know if these are needed or not, I don't know about them.

**Comment by k2b6s9j** [comment] 2015-04-02 20:03
Oh my gosh. Thank you! This is great. I must experiment now!

**Comment by k2b6s9j** [comment] 2015-05-02 05:57
Ok. I'm absolutely stumped. I'm trying to write my binding for the JNI and I'm having just the worst luck. The compiler keeps throwing me an error when I try to call a JNI method. At first I thought I had declared it incorrectly, but then I began to investigate if I needed to link properly and was completely lost there. So I'm going to post the compiler error I get and hope one of y'all can point me in the right direction.

```
; ModuleID = 'JCrystal'

%String = type { i32, i32, i32, i8 }
%"struct.LibJNI::JavaVM" = type {}
%"struct.LibJNI::JavaVMInitArgs" = type { i32, i32, %"struct.LibJNI::JavaVMOption", i32 }
%"struct.LibJNI::JavaVMOption" = type { i32*, i8 }

@symbol_table = external global [1 x %String*]

define void @"*JCrystal::create_vm<struct.LibJNI::JavaVM>:Void"(%"struct.LibJNI::JavaVM"* byval %jvm) {
alloca:
  %vm_args = alloca %"struct.LibJNI::JavaVMInitArgs"
  %options = alloca %"struct.LibJNI::JavaVMOption"
  %ret = alloca i64

entry:                                            ; No predecessors!
  %0 = getelementptr inbounds %"struct.LibJNI::JavaVMInitArgs"* %vm_args, i32 0, i32 0
  store i32 65537, i32* %0
  %1 = getelementptr inbounds %"struct.LibJNI::JavaVMInitArgs"* %vm_args, i32 0, i32 1
  store i32 1, i32* %1
  %2 = getelementptr inbounds %"struct.LibJNI::JavaVMInitArgs"* %vm_args, i32 0, i32 3
  store i32 0, i32* %2
}
Unhandled Type::Kind in size: Void
*raise<String>:NoReturn +70 [4483193734]
*LLVM::ABI::X86_64#size<LLVM::ABI::X86_64, LLVM::Type>:Int32 +715 [4486113563]
*LLVM::ABI::X86_64#classify<LLVM::ABI::X86_64, LLVM::Type>:Array(LLVM::ABI::X86_64::RegClass) +16 [4486111552]
*LLVM::ABI::X86_64#abi_info<LLVM::ABI::X86_64, Array(LLVM::Type), LLVM::Type, Bool>:LLVM::ABI::FunctionType +408 [4486111016]
*Crystal::CodeGenVisitor#abi_info<Crystal::CodeGenVisitor, Crystal::External>:LLVM::ABI::FunctionType +491 [4486107467]
*Crystal::CodeGenVisitor#prepare_call_args_external<Crystal::CodeGenVisitor, Crystal::Call, Crystal::External, Crystal::Type+>:{Array(LLVM::Value), Bool} +83 [4486227459]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:(Nil | Bool) +293 [4486189205]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +50 [4486164114]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:(Nil | Bool) +137 [4486322345]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +3237 [4486167301]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +1908 [4486318276]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2452 [4486166516]
*Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def+, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +1656 [4486251512]
*Crystal::CodeGenVisitor#target_def_fun<Crystal::CodeGenVisitor, Crystal::Def+, Crystal::Type+>:LLVM::Function +2164 [4486246852]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:(Nil | Bool) +4105 [4486193017]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +50 [4486164114]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Assign>:(Nil | Bool) +137 [4486322345]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +3237 [4486167301]
*Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Expressions>:Bool +1908 [4486318276]
*Crystal::Program#build<Crystal::Program, Crystal::Expressions, (Nil | String | Bool | Array(String)), Bool, LLVM::Module, Bool>:Hash(String, LLVM::Module) +113 [4486042641]
*Crystal::Compiler#build<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:(Nil | Bool) +3436 [4486029980]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4945 [4485306577]
*Crystal::Command::run_command<Array(String)>:Nil +388 [4483238580]
*Crystal::Command::run<Array(String)>:(Nil | CFileIO | File | Bool | Crystal::Compiler::Result | Array(Crystal::Init::View+:Class)) +67 [4483212595]
main +15985 [4483210449]
```

**Comment by asterite** [comment] 2015-05-02 14:17
Yes, any time the compiler tells you that you've found a bug, it's a bug :-)

Thanks for reporting, I'll take a look at it. Next time please provide a way to reproduce this. For now I found that it happens if you execute [this file](https://github.com/k2b6s9j/jcrystal/blob/master/samples/new_java_vm.cr).

**Comment by k2b6s9j** [comment] 2015-05-02 17:40
Sorry. Posted the comment late at night, totally forgot to post the example.

**Comment by asterite** [comment] 2015-06-16 18:07
I'll close this. Using things like JNI extensions or Ruby extensions in Crystal isn't its purpose for now because of it having a GC. There's also the thing that every time you compile an app we assign potentially different IDs to types, so different JNI/Ruby extensions won't be compatible... at least not now.

**Closed by asterite** 2015-06-16 18:07 UTC
Labels: bug, question
