### ISSUE TITLE
Inheritance + class variable + method missing = compiler error

### ISSUE THREAD

**Issue by dbackeus** [manastech/crystal#1131] opened 2015-08-08 16:04 UTC
The code:
http://play.crystal-lang.org/#/r/ak0

It breaks down on the second instantiation since `typeof(@child)` changes from `Child` to `Parent` and I suppose the compiler doesn't know which classvar to expect anymore?

Was really tricky to find the cause and minimum way of reproducing from the larger codebase I'm working on. Hope we can actually get it to work apart from avoiding compiler panic.

Might be related to: https://github.com/manastech/crystal/issues/916

**Comment by asterite** [comment] 2015-08-10 00:09
Yes, this is a duplicate of #916, I'll comment there.

**Closed by asterite** 2015-08-10 00:09 UTC
Labels: bug, duplicate
