### ISSUE TITLE
"with self yield" and instance/class variables

### ISSUE THREAD

**Issue by Exilor** [manastech/crystal#510] opened 2015-04-03 11:51 UTC
```ruby
class Foo
  @@class_var = 1

  def initialize
    @instance_var = 2
  end

  def bar
    with self yield
  end
end

Foo.new.bar { @instance_var } # => Error: you've found a bug in the Crystal compiler. Please open an issue
Foo.new.bar { @@class_var } # => 1
```
This either needs an actual error message for both cases if they shouldn't work (as per issue #166) or, if @asterite has changed his mind about it, have the first case work.

**Comment by asterite** [comment] 2015-04-03 14:14
This is kind of a duplicate of #234, although I didn't know it worked for class vars. It should give an error in both cases.

I'll fix it soon, now it was discovered by more than one :-P

**Closed** 2015-04-03 21:00 UTC
Labels: bug, duplicate

**Comment by asterite** [comment] 2015-04-03 21:04
So, `@instance_var` will now give an error (because the top-level doesn't have instance vars). If you try it inside a class it'll work (access that class's instance var).

However, `@@class_var` works on the top-level (they are vars of the top-level program, similar to globals) so the second line will work and be `nil`. We might change that in the future (not sure why @@class_var works at the top-level, maybe it was easier to do that than to give a compile-time error).

The whole reason behind making instance vars not bind to the `with ... yield` scope is the following snippet:

```ruby
class Foo
  def foo(&block)
    instance_eval &block
  end
end

class Bar
  def initialize
    @x = 1
  end

  def bar
    Foo.new.foo do
      @x + 1
    end
  end
end

puts Bar.new.bar
```

What do you expect that method to print? Well, it crashes with "undefined method `+' for nil:NilClass (NoMethodError)", because `@x` refers to an instance variable of Bar. And here we were lucky and Bar didn't define an `@x` variable, but if it did, good luck debugging that :-)

**Comment by Exilor** [comment] 2015-04-03 21:24
I think that whoever toys with ```with self yield``` and instance variables should accept the responsibility and potential brain damage that may arise. I'm always against taking "powers" away from the programmer.

However this issue is only meant to report that error, not try to persuade you to allow ```{ @instance_var }``` to work :smile:
