### ISSUE TITLE
Monkey-patched functions called by unmangled functions preserve old definition, unless called by a mangled function

### ISSUE THREAD

**Issue by Philpax** [manastech/crystal#1768] opened 2015-10-18 10:39 UTC
The title's a little long, but this is an oddly specific issue:
```crystal
def test(msg)
    puts "Old definition! " + msg
end

fun handler_fun() : Void
    test "Testing 123"
end

def handler_def()
    test "Testing 123"
end

def test(msg)
	puts "New definition! " + msg
end

handler_fun
#handler_def
```
results in
```
Old definition! Testing 123
```

Uncomment the last line and this happens:
```
New definition! Testing 123
New definition! Testing 123
```

Note that the use of arguments in the monkey-patched function is important (otherwise both function calls use the new definition, as expected).

My original hypothesis was that the `fun` was being instantiated at the definition site, while the `def` was being instantiated at the call site, but this doesn't account for the behaviour seen above.

**Comment by asterite** [comment] 2015-10-18 13:50
Duplicate of #1104 . We need to define what to do with method definitions and code that uses them.

**Closed by asterite** 2015-10-18 13:50 UTC
Labels: bug, compiler
