### ISSUE TITLE
Error during compiling spec/all_spec.cr with --release flag - Killed: 9

### ISSUE THREAD

**Issue by radarek** [manastech/crystal#1541] opened 2015-09-21 13:30 UTC
I tried to compile with --release flag all specs (current master 124e1b194990e74cac8934ddbf92806e988af314) but I got error during compilation. Here is output:

```
$ time bin/crystal build --release spec/all_spec.cr -o .build/all_spec-release
Using compiled compiler at .build/crystal
Killed: 9

real	38m21.965s
user	35m42.118s
sys	1m17.010s

$ bin/crystal -v
Using compiled compiler at .build/crystal
Crystal 0.8.0 [124e1b1] (pon 21 wrz 06:56:32 2015 UTC)
```

OS: Mac OSX 10.10.5.

**Comment by jhass** [comment] 2015-09-21 14:09
You ran out of resources and the OS killed the process. That's why we don't do it, the LLVM codegen takes insane amounts of memory (in release mode), and  we're not sure yet if we can do anything about it.

**Comment by jhass** [comment] 2015-09-21 14:09
Also duplicate of #768

**Comment by asterite** [comment] 2015-09-21 15:45
Closing because it's a duplicate

**Closed by asterite** 2015-09-21 15:45 UTC
Labels: duplicate
