### ISSUE TITLE
Need alias_method

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2041] opened 2016-01-21 14:59 UTC
Due to the lack of an `alias_method` keyword, I've implemented my own. Unfortunately, I can't make it support block arguments:

```
macro alias_method(newname, oldname)
	def {{newname.id}}(*args)
		{{oldname.id}}(*args)
	end
end

def a; yield; end
alias_method b, a

b() { }    # ERROR: 'b' is not expected to be invoked with a block, but a block was given
```

I can't even write two macros, with different names, because there is no way to forward blocks without knowing their signature. Besides, that would be an ugly solution.

Can we have a real `alias_method` please?

**Comment by asterite** [comment] 2016-01-21 15:04
Duplicate of #1966

**Comment by asterite** [comment] 2016-01-21 15:04
We *might* add this if we ever make `alias_method` work with blocks and named arguments.

**Closed by asterite** 2016-01-21 15:04 UTC

**Comment by stugol** [comment] 2016-01-21 15:18
I consider it to be fairly important.
