### ISSUE TITLE
Array::each works different than ruby

### ISSUE THREAD

**Issue by jsaak** [manastech/crystal#1457] opened 2015-09-12 14:09 UTC
given this program
```
[[1,"A"],[2,"B"]].each do |a,b|
  puts a
  puts b
end
```

```
$ crystal test.cr
[1, "A"]

[2, "B"]

$ ruby test.cr   
1
A
2
B
```

i have not seen anywhere mentioning that this will work differently
i am not sure if this is a bug or intentional
(i would not miss this feature of ruby very much)

**Comment by jhass** [comment] 2015-09-12 14:13
This is because Crystal has no autosplat. I'm closing this as a duplicate of #392 since it won't ever happen for nested arrays. Also related to #132

**Closed by jhass** 2015-09-12 14:13 UTC
Labels: duplicate

**Comment by jsaak** [comment] 2015-09-12 15:09
please indicate somewhere in documentation , that this is the expected behaviour

**Comment by jhass** [comment] 2015-09-12 15:10
I guess we should add it to https://github.com/manastech/crystal/wiki/Crystal-for-Rubyists

**Comment by jsaak** [comment] 2015-09-12 17:01
yup, no one else in the world would try this, only rubyists

**Comment by Nakilon** [comment] 2015-09-13 11:20
Try what? Doesn't `for i, j in a` work in Python?
