### ISSUE TITLE
Incorporate 'and' and 'or' logic operators as well.

### ISSUE THREAD

**Issue by konsolebox** [manastech/crystal#1449] opened 2015-09-11 19:39 UTC
Please consider adding `and` and `or` with the same precedence as Ruby`s (equal precedence).

I prefer using them over `&&` and `||` as I find them more readable in the code and more consistent when having longer sequences.  `&&` having higher precedence than `||` to me adds confusion in which you are forced to use `()` to prevent the precedence effect.   `and` and `or` having equal precedence show clarity and is faster to write code with (because you don't have to think about precedence, only grouping when necessary).  `and` and `or` is also more appropriate for single-line reverse if or unless-like statements.   `and` and `or` is also good for creating logic chains where jumps happen.  Using `&&` and `||` for that where you have to unnecessarily group is far from practical.

Anyway, whatever one coder's preference is, I don`t think adding the operators would hurt as it has been part of Ruby.  There would also be unnecessary replace-and-verify work for converting Ruby code that uses them to Crystal code if those two operators don't exist.  IMO the language needs them to make itself essentially complete.

**Comment by jhass** [comment] 2015-09-11 19:49
It's quite by design that they're omitted, it's listed as explicit difference: https://github.com/manastech/crystal/wiki/Crystal-for-Rubyists#omitted-language-constructs

The difference is entirely non-obvious to newbies and it's one more concept to learn. It's hidden behaviour and thus makes the code less obvious as it requires inherent knowledge. Many Ruby styleguides recommend `&&` and `||` because their precedence rules are closer to what you're used to from other languages and what you naturally expect (`foo = a && b` vs `foo = a and b` is just one example). In fact I had to explain logic bugs to a newbie in #ruby more than once based on that.

I'd also argue that `return if done?` reads a lot better than `done? and return`, the latter hides what's actually happening behind the condition and the conditionally is not what you're used to from natural language.

**Comment by konsolebox** [comment] 2015-09-11 21:20
@jhass

From the link you provided, it says *"use `&&` and `||` instead with suitable parenthesis to indicate precedence"*.  I don't see why you'd even need to indicate precedence when you could just read it from left to right and use `()` to group things.

You can actually argue that natural languages like C use higher precedence for `&&` however, I believe Ruby was also majorly based on the shell in which case `&&` and `||` have equal precedence.  You can tell that the Crystal language is more on the programming side or on the side of C but I don't really see the significance of it.  We're still free to choose which operators to use anyway.  `and` and `or` doesn't look like `&&` and `||`, and you can't find them in C so it should be easy to distinguish how they differ from the other two.  I also don't find enough weight on an argument that we should avoid it just because newbies don't find the difference between the two sets of operators.  It doesn't apply to everyone.

I also don't use `cond and action` but if we're going to allow methods like `cond && action` then we might as well give it to `and` since it's better.

And I don't see why we should restrict ourselves on following the natural language if the natural language would turn out to be more difficult to follow.  I don't see why we can't have a choice.  And I'm not saying this because `&&` and `||` is difficult to follow for me.  It just turns out that using `and` and `or` is way easier and more consistent in many ways.  And I love consistency, over following community practice.

If the reason behind this is to keep the community in line with a traditional practice rather than giving them a choice, then I might as well give it up.

My argument on code compatibility still stands.

**Comment by jhass** [comment] 2015-09-11 21:23
Natural language means English etc., https://en.wikipedia.org/wiki/Natural_language

**Comment by kirbyfan64** [comment] 2015-09-11 21:33
> I also don't find enough weight on an argument that we should avoid it just because newbies don't find the difference between the two sets of operators.

I came from Python. The first time I tried Ruby, I hated it. Part of the reason is that I assumed that Python's `and` and `or` would work in Ruby. It did, but the result was somewhat...*unexpected*.

In reality, most of Ruby's criticism comes from these little things that Crystal fixes. Because, one day, you will be slightly sleepy, use `and` instead of `&&`, and put this tiny little bug in your code that will come up later. 

> If the reason behind this is to keep the community in line with a traditional practice rather than giving them a choice, then I might as well give it up.

You're missing the point. It's not traditional practice. It's simply a differing of opinion. Also, it'd be kind of sad if you gave up a programming language because of one decision. There are languages whose communities are crap, but I still use the language.

**Comment by konsolebox** [comment] 2015-09-11 21:33
@jhass 

If that's what you meant about natural language, `and`, `or` and `not` are more natural than `&&`, `||` and `!`.

I also want to add that `cond and action` is more appropriate than `action if cond` if `cond` turns out to be an action as well itself: `action and action` or `action or action` e.g. `do_something or exit`.  And with `&&` or `||` precedence, I find them less appropriate for calling actions.

**Comment by jhass** [comment] 2015-09-11 21:48
You're still missing my point about natural language. "if", "unless", "while" and "until" are words that imply conditionally in natural speech, "bring milk if you go to the grocery", "turn off the light unless it's dark" and so on. "and" and "or" do not, "go to the grocery and bring milk", "it's dark or turn off the light" have a very different meaning or don't even make sense, there's no conditionally. Using `&&`/`||` for control flow is simply impractical due to their precedence rules, so you retain the conditionally by using them in conjunction with `if` etc.

**Comment by konsolebox** [comment] 2015-09-11 23:24
@jhass 

Sorry I thought you were talking about natural language when applied to `if`, `while`, `until`, `unless`, etc. and not on single lines like `action and action`.  Because if it would have been the case, `and`, `or` and `not` would have been more fitting to be used with them, with respect to natural language.

Still if it's about comparing `action if action` vs. `action and action`, what's the difference?  Even that is still not English.  It's as if you're saying *"Drink if eat."* or *"If eat, drink."*  You can't compare them by natural language as neither can apply well like it.  Actually most of the time, natural language doesn't come well with computer language.  An example I can give is Ruby's chain of blocks.

`action and action` is clearer than `action if action` as it stands better as a *computer language phrase*.  The actions are also placed in order.  Not that the second actions comes before the first.  You can have three or four consecutive actions and you would still be fine with one line, whereas with `if`, you may end up needing multiple lines, if not multiple blocks to wrap-up the actions.

**Comment by asterite** [comment] 2015-09-11 23:31
I don't see the need for 'and'  and 'or' if you can use parentheses, and that doesn't happen often.

I also faced the same as kirybyfan, I liked the 'and'  and 'or' until I found out they have a slightly different meaning (precedence), and then I decided I would stop using them to avoid bugs.

In the company I work nobody uses them. And I think they are discouraged in the Ruby community. So they are not in Crystal.

Adding them would just add a tiny bit of convenience for things you can already easily do (use parentheses) and mean new things to learn, potential mistakes, etc.

**Comment by bcardiff** [comment] 2015-09-12 00:00
I have only find them useful for writing things like.

```
render something and return if condition
```

Clearly in a rails controller.
And sometimes I had try to use them just because they exists. Checking if they were more suitable. But when someone finds that code, since they are not used to, it's harder to understand.
Fewer (good) options, easier to understand.

And last but not least, having two operations that are pronounced the same but have different semantics is a bad idea IMO.

@konsolebox please stay around despite your first request/topic seems to be receiving a :-1: so far. The discussions and points of view are welcome, really. :-). Whatever, positive or negative, conclusion we achieve is a way to exposing and clarifying some decisions as group/community.

**Comment by konsolebox** [comment] 2015-09-12 10:46
@asterite

> I don't see the need for 'and' and 'or' if you can use parentheses, and that doesn't happen often.

`do_something or raise error` happens significantly often.  And that's just one example in general scope.

> Adding them would just add a tiny bit of convenience for things you can already easily do (use parentheses) and mean new things to learn, potential mistakes, etc.

The convenience of having slick and consistent code is not tiny for me.  Same would apply to users who knows how to use them and uses them.  It's pain in the brain and an unnecessary obstacle for writing and studying code if I wouldn't have it.  Conciseness is a must.  Learning only happens once.  Potential mistakes don't happen when you know how to use them.  And there's even less potential mistakes on using `and`/`or` vs. using `&&`/`||` as the former has equal precedence while the latter doesn't.  Also having a precedence near the lowest levels could also mean bigger scope.  Instances where you forgot to use parentheses if you would be using `&&`/`||` may not hurt you if you're using `and`/`or` instead.  Remembering the rule to use `&&` and `||` only during assignments and use `and` and `or` anywhere is pretty much easier than having to remember how to use `&&` and `||` where their precedence could affect operators differently as they're in the middle level.

@bcardiff 

> Fewer (good) options, easier to understand.   And last but not least, having two operations that are pronounced the same but have different semantics is a bad idea IMO.

Not when those versions have different purposes on which each is useful.  They may sound the same but they're pretty much easy to distinguish visually.  `and` and `or` have different lexical compositions to `&&` and `||` and is more similar to `until`, `if`, etc.  One could just remember that they are almost on the same level as word-like keywords, and just forget the precedence of everything else.

@asterite, @bcardiff 

> And I think they are discouraged in the Ruby community. So they are not in Crystal.
> But when someone finds that code, since they are not used to, it's harder to understand.

And the community avoids it and sees it as bad simply because people who chose not to try to understand it well would find it confusing and tend to have mistakes using it.  Instead of trying to educate them how to use it properly and let them gain the benefits of using it, they simply just tell them to avoid it.

@bcardiff

> please stay around despite your first request/topic seems to be receiving a :-1: so far.

All I can say is that I don't want to code without it.

If `and`/`or` doesn't become part of Crystal then I wouldn't mind just sticking to Ruby.  I wouldn't change my practice and lose its convenience and change my codes just for the sake of following strict and narrow conformancy.  Note that in many cases, people would want their to work both in Ruby and Crystal if they would want it to make it work with Crystal.  Or at least they would want it to be easily portable in both directions.  That's what I find.

> Whatever, positive or negative, conclusion we achieve is a way to exposing and clarifying some decisions as group/community.

There are users that know what they are doing and don't just follow what the community says so, and this decision would affect them.  The community's point view is just a point of view of many and is not always right or is not always applicable in all cases.  Forcing conformity to a difficult larger-community-induced standard and relying on minimalism just to avoid novice mistakes rather than allowing flexibility, choice and compatibility would certainly affect how some people would decide on using the language, and/or porting their codes into it.

**Comment by kirbyfan64** [comment] 2015-09-12 13:52
@konsolebox

> Conciseness is a must.

...sure you're not an APL or array-based programmer? :)

> All I can say is that I don't want to code without it. ... I wouldn't change my practice and lose its convenience and change my codes just for the sake of following strict and narrow conformancy.

You know, languages have tradeoffs. I code frequently in C++ even though is has insane complexity. It has issues, but they don't stop me liking everything else.

When I'm in Crystal, I still miss Python-style indentation and screw up my `end`s when modifying code. However, the rest of the language is good enough for me to still use it.

> Forcing conformity to a difficult larger-community-induced standard and relying on minimalism just to avoid novice mistakes rather than allowing flexibility, choice and compatibility would certainly affect how some people would decide on using the language, and/or porting their codes into it.

1. They're not novice mistakes. Ask any experienced C programmer that screwed up their program because they forgot the difference between `&&` and `||` precedence momentarily or accidentally entered `=` instead of `==`.

2. It's all about opinion. Different people maintaining different languages have different opinions. It's really not bad, regardless of whether or not you like it. I really really really really **REALLY** hate Go and everything around it, but they have some strong opinions, and I respect them.

So, just for fun, here's a closing quote by Bjarne Stroustrop:

> There are only two kinds of languages: the ones people complain about and the ones nobody uses.

**Comment by waterlink** [comment] 2015-09-12 15:50
My 2 coins about `&&, ||` and `and, or` operations:

Originally they came out of boolean math, not `C` language at all. In
boolean math `&&` is the same for booleans as multiplication for numbers;
`||` is the same as addition for numbers. So naturally, `&&` has stronger
precedence.

I have no idea, where `and` and `or` has came from. If you know their
origin, please tell me.
If it is an English language, that when you combine `and` and `or`
together, you will probably have `coma` (or other) punctuation somewhere -
to me this is analog of our parenthesis in math and programming.

I have no problem with having `and` and `or`, though I never used them in
Ruby. If I would see code like `action or raise Error` - it is OK-ish. But
if I see something like `action or action2 and action3 or raise Error`,
then I will refactor this out into 2-3 distinct methods (or even classes)
immediately, because that expression hides too much logic, that could be
probably important domain knowledge, and makes my mind stop to think,
instead of just reading code in a flow.


--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-12 15:52 GMT+02:00 Ryan Gonzalez <notifications@github.com>:

**Comment by kirbyfan64** [comment] 2015-09-12 16:12
@waterlink

> I have no idea, where `and` and `or` has came from.

Pascal.

**Comment by waterlink** [comment] 2015-09-12 16:41
@kirbyfan64 AFAIK `and` and `or` there had proper math precedence, so that when you combine `and`s and `or`s, parenthesis are still may be required.

**Comment by asterite** [comment] 2015-09-14 14:06
We already use `something || raise` in several places, for example: https://github.com/manastech/crystal/blob/master/src/enum.cr#L292

You need parenthesis, but I believe this makes it easier to understand the code, you don't need to think about precedence rules at all.

**Comment by kirbyfan64** [comment] 2015-09-14 14:13
@waterlink Oh. Then Perl.

**Comment by waterlink** [comment] 2015-09-14 19:27
Yes, Perl is the one it is going from :) And some 5th generation languages
have this feature too (Prolog or something).

--
Best Regards,
Alexey Fedorov,
Sr Ruby, Clojure, Crystal, Golang Developer,
Microservices Backend Engineer,
+49 15757 486 476

2015-09-14 16:13 GMT+02:00 Ryan Gonzalez <notifications@github.com>:

**Comment by ozra** [comment] 2015-09-29 20:12
Beating dead horse here, but, I like `and`, `or`, `is` and `isnt` - but with same precedence as the respective signs-based version.

**Comment by konsolebox** [comment] 2015-09-30 07:02
@ozra Having different precedence settings to Ruby would be a disaster.

**Comment by asterite** [comment] 2015-09-30 16:24
To stop the discussion going on, I'll close this. Use parenthesis, it's pretty simple and much easier to understand than having two separate operators with the same meaning but different precedence.

**Closed by asterite** 2015-09-30 16:24 UTC
Labels: compiler, draft, RFC

**Comment by pannous** [comment] 2016-10-15 00:04
Why not add 'and' and 'or' as aliases for && and || with the same precedence and without special meaning?

We can rather abolish ||= which isn't even syntactic 'suggar'.

**Comment by pannous** [comment] 2016-10-15 00:09
@konsolebox the only disaster is that in ruby these operators apparently(?) have equal precedence. Didn't even know that.

**Comment by konsolebox** [comment] 2016-10-15 02:29
@pannous I'm not sure what you mean.  Do you mean `and` and `or` having equal precedence is a disaster?  Or Crystal having difference precedence settings of operators to Ruby a disaster?  If it's the former, all I say is that you don't how helpful it is to those who know how to use it.  And please read my other comments.

Also, using a high-precedence operator as a "flow control" operator (e.g. `action || raise "message"`) is an abomination.

**Comment by pannous** [comment] 2016-10-15 07:35
I meant the former, though I can't confirm the problem:
```ruby
> 1 and 0 or 1
 => 0 
> 1 && 0 || 1
 => 0 
```
All we want is the same syntax and behavior in crystal.
It is a beautiful *standard* by now in ruby, python and others.

Whether to allow boolean operators in "flow control" is another discussion independent of the || vs 'or' question. 
```crystal
file.delete() or continue
```

So I completely agree with your initial suggestion to add an 'and' operator (good),
though I disagree about deviating from its *standard* precedence.

**Comment by pannous** [comment] 2016-10-15 07:49
@asterite the horrible precedence problem seems independent of the syntactic question, so I suggest to add 'and' and 'or' anyways, just make it behave exactly like && and ||.

**Comment by pannous** [comment] 2016-10-15 07:49
Whether to allow boolean operators in "flow control" is another discussion independent of the || vs 'or' question. 
```crystal
file.delete() or continue
```

**Comment by pannous** [comment] 2016-10-15 08:07
>>> True or True and False
True

**Comment by konsolebox** [comment] 2016-10-15 10:04
>  though I disagree about deviating from its standard mathematical/python precedence.

`&&` and `||` does that (i.e. follow the implementation of C), but `and` and `or` follows the implementation of the shell.   Some implementation that is unfamiliar to the typical members of the community is not necessarily a bug, so stop calling it like one.  And please stop mentioning Python as if it's a master language, and that anything that it implements is a standard.  Ruby has its own predecessors, and Python is not one of them.  The times they first appeared also only differ by 4 years.

**Comment by pannous** [comment] 2016-10-15 10:38
I love ruby and its community, but 'calculating' `1 && 0 || 1` to 0 is either a bug, laziness or madness.

**Comment by RX14** [comment] 2016-10-15 10:43
@pannous both zero and one are truthy in ruby. This means `1 && 0` returns `0`, because they're both truthy so it returns the right hand side. Then the rhs of `||` never gets evaluated because the lhs is true. `true && false || true` is `true` as you would expect.

**Comment by asterite** [comment] 2016-10-15 14:37
@pannous Unlike Ruby, we *generally* avoid aliases. If we add `and` and `or` as aliases of `&&` and `||` then some will use the former and some will use the later. In a project of 2 or more people this will cause two coding styles, and eventually there will be a discussion about which one to use. All of that will just be lost time.

If we never add those aliases such discussions will never exist and code will look uniform to everyone. This is the same reason we have a non-configurable formatter. I know (because I read some complaints) that the formatter might be too strict, but that only brings a tiny small frustration to some developers, but still removes those discussions from the table so time isn't lost.

**Comment by konsolebox** [comment] 2016-10-16 02:34
> Unlike Ruby, we generally avoid aliases.

Again just to clarify, `and`/`or` is not an alias of `&&`/`||`.

> but that only brings a tiny small frustration to some developers, but still removes those discussions from the table so time isn't lost.

But still narrow-sighted.  In the long run, people would not feel happy about a language that's full of conservative restrictions, especially if the remaining solutions become a hack.  Consistency should always be a priority.  Minimalism is good, but not when you make things simpler than what it could be.

**Comment by RX14** [comment] 2016-10-16 09:10
@konsolebox Adding `and` and `or` in the ruby sense would violate the principle of least surprise for *anyone* who hasn't used those operators in Ruby. This language isn't made just for ruby developers. 

Adding `and` and `or` as aliases goes against @asterite's wish not to have aliases.

Therefore they shouldn't be added.

**Comment by konsolebox** [comment] 2016-10-16 11:03
> This language isn't made just for ruby developers. 

But there are more Ruby developers than those that aren't.  Those who learn Crystal would also tend to learn Ruby.

Consistency also comes first before anything, even before that principle of least surprise, which I think doesn't even apply, because if you're using a language, it's your responsibility to learn how its basic operators work.  Principle of least surprise should apply to things that you wouldn't easily recognize while you write your code (like runtime stuff), and that would exclude the operators which are well documented.

> Adding and and or as aliases goes against @asterite's wish not to have aliases.

I also don't like adding them "as aliases".  I'm just making it sure that the points of this discussion don't become mislead.

> Therefore they shouldn't be added.

Yes if they would be added in that manner, but no if not.

**Comment by RX14** [comment] 2016-10-16 11:28
@konsolebox principle of least surprise would be `and` and `or` being the same as `&&` and `||` in other languages. There's a reason people avoid `and` in ruby, and that's because it's simply confusing.

As for consistency, here crystal is consistent with ruby and every other language with `&&` and `||` in that they work the same and have the same precedence. Being consistent with ruby by adding ruby's `and` and `or` (which are stupid) is absolutely NOT a goal, we're already a very different language then ruby with a load of old, crufty and confusing syntax removed. This is one of the worst ruby syntaxes and i'm glad it's gone.

**Comment by konsolebox** [comment] 2016-10-16 11:46
> principle of least surprise would be `and` and `or` being the same as && and || in other languages.

Again, that's not it.  There's a clear difference if you know to read the documentation.  Also, people do get surprised because the majority in the community promote such bad practice, which is to stay ignorant about how the operators work, and how they could properly use them.  You should also know that some users also get confused with the in-equal precedence of  `&&` and `||`, like shell-scripters.  Or at the very least you can say that they aren't surprised with how `and` and `or` works.

Also, what language has both `and` and `or`, and `&&` and `||` where they have same functions?  How many?

> `and` and `or` (which are stupid) 

They aren't stupid.  `&&` and `||` being used to function as a "flow-control" operator where low and equal precedence is required is stupid.

**Comment by chaniks** [comment] 2016-10-16 11:58
I think @RX14 has already made a good point.

This thread already showed that not many of us knew the difference between `&&` and `and`.  It means that this feature is not essential, it increases the learning period of the language, and it also makes some confusion.

I myself also used ruby for 11 years. Missing `and` and `or` is not a big deal.

p.s. But I won't be too opposing either because `and` and `or` look cute. 😉

**Comment by RX14** [comment] 2016-10-16 12:36
@konsolebox having to read the documentation is the exact point i'm making. The fact that you have to read the documentation to realise they are different from `&&` and `||` means it violates the principle of least surprise.

You shouldn't *have* to read the language documentation to read a basic boolean expression. You should be able to assume it works exactly like java, C#, C++, ruby, C, go. And as far as i'm aware `||` and `&&` work the same in all of those languages. Adding `and` and `or` as aliases would confuse the ruby crowd, and adding them as in ruby would confuse everyone else, just like they confuse newcomers in ruby.

**Comment by konsolebox** [comment] 2016-10-16 14:18
@RX14 And then again I would say the principle of least surprise is not about that, because `and` and `or` has their own useful functions different from `&&` and `||`, and because of that reading the documentation or learning about the difference is a necessity.  We're going in circles.

> Adding `and` and `or` as aliases 

They're not aliases.

>  just like they confuse newcomers in ruby.

It can't be helped because `and` and `or` has to keep their own functions.  And the solution is not to avoid them, but to learn about them.

**Comment by konsolebox** [comment] 2016-10-17 09:35
@ozra Yep, you can say what you want, and so will I for the sake of this discussion.  I understand that other people would choose to compromise, but I'd still give my point.

> a bunch of assumptions that are not in line with reality

And can you confirm that on your part?  Don't say that I'm making assumptions.  I give my perception, just like what you're doing right now.  And this is not just about all the people in this thread.

Also, when did I deny to acknowledge that you have your own choices?  This is why I'm honestly trying to defeat your with arguments, just like how it is done in any discussion.

> Life is full of compromises.

Philosophical.  I won't go there.  But it's good that you admit that you prefer to lean on it.

You know what, at one point Crystal should tone down its description that it has a Ruby-like syntax, because it's a bit misleading.

**Comment by Sija** [comment] 2016-10-17 09:37
@konsolebox Even though they're nice to read, having `and` and `or` following Ruby logic (ie. lower precedence) would invite a host of bugs made by unaware developers, see one of a more popular answer on SO regarding this topic: http://stackoverflow.com/questions/1426826/difference-between-and-and-in-ruby. On the other side, if they'd have the same precedence as `&&` and `||` they'd differ from Ruby in this regard and be aliases which @asterite clearly opposed.

**Comment by konsolebox** [comment] 2016-10-17 09:44
@Sija I'm not one who's wanting it to have same precedence as `&&` and `||`.  Unaware developers being unaware is their own fault, and partly the large part of the community that promotes oblivion of those functions.

**Comment by ozra** [comment] 2016-10-17 10:33
@konsolebox, sorry for being vague, my comment was obviously referring to:

> Those who learn Crystal would also tend to learn Ruby.

Which I don't think is true at all. (That many _already_ know it - yes, but that those of us coming from other languages would do - no). But this is my perception. And perception is to a great extent based on assumption.

It seems to me you're basically attacking all developers that don't agree with your world view, not just arguing with facts.

Anyway. I've argued for my favoured outcome. And I soberly accept the consensus of the operators not being wanted at all _in Crystal_, in any of the proposed variants.

**Comment by RX14** [comment] 2016-10-17 10:33
@konsolebox your attitude is that you know how they work therefore everyone else should learn. That attitude isn't conducive to a simple to learn, easy to read language. 

You seems to accept that adding `and` and `or` would mean that people would need to read the documentation to learn how they work. If you weigh the disadvantage of confusion with that you *gain*, that is how we should decide whether to add them. 

So what do we gain from adding `and` and `or`? Can you come up with some examples which are written better enough using these operators to justify their addition to the language given their downsides?

**Comment by pannous** [comment] 2016-10-17 10:46
@konsolebox just to be sure you really want the exact same Ruby behavior: 
https://news.ycombinator.com/item?id=12723888

**Comment by konsolebox** [comment] 2016-10-17 11:31
@RX14 Read my early comments.

@pannous None of those examples have meaning.

**Comment by pannous** [comment] 2016-10-17 11:33
So they should be banned, as per the community style guide? 
https://github.com/bbatsov/ruby-style-guide/commit/5920497452c1f6f604742a735f5684e86d4c0003

**Comment by konsolebox** [comment] 2016-10-17 12:35
@pannous I don't see your latest message.  Did you remove it?

> So they should be banned, as per the community style guide?
> bbatsov/ruby-style-guide@5920497

Thanks for sharing the link.  So have you seen other people counter-argued with the idea of banning those operators?

https://github.com/bbatsov/ruby-style-guide/commit/5920497452c1f6f604742a735f5684e86d4c0003#commitcomment-7783051
https://github.com/bbatsov/ruby-style-guide/issues/244
https://github.com/bbatsov/ruby-style-guide/pull/489#issuecomment-213457203

**Comment by kirbyfan64** [comment] 2016-10-17 14:07
*sigh* I thought this thread was dead already...
