### ISSUE TITLE
I wish Crystal would be more intuitive...? :D

### ISSUE THREAD

**Issue by sardaukar** [manastech/crystal#1108] opened 2015-08-05 23:18 UTC
```
operands = [] of { Symbol, (UInt8 | UInt16) }

operands << { :example, 1.to_u8 }
````

It would be super intuitive for this to work. Instead, we have to write
```
operands = [] of { Symbol, UInt8 } | {Symbol, UInt16}

operands << { :example, 1.to_u8 }
```

or 

```
operands = [] of { Symbol, (UInt8 | UInt16) }

operands << { :example, 1.to_u8 as (UInt8|UInt16) }
```

**Comment by kostya** [comment] 2015-08-05 23:26
why not use record?
http://play.crystal-lang.org/#/r/9vl

**Comment by sardaukar** [comment] 2015-08-05 23:30
I didn't know about it. Still seems counter intuitive.

**Comment by bcardiff** [comment] 2015-08-06 00:21
@sardaukar this indeed a case of https://github.com/manastech/crystal/issues/357

We need teach the compiler that `{ Symbol, UInt8 } <: { Symbol, (UInt8 | UInt16) }`.

Since the tuple is immutable that is a safe & sound thing to do.

**Comment by ozra** [comment] 2015-08-06 10:34
What is records? Can't find it in man??

**Comment by asterite** [comment] 2015-08-06 13:50
@ozra It's the [record](http://crystal-lang.org/api/toplevel.html#record%28name%2C%20%2Afields%29-macro) macro, which isn't documented, but it basically defines an immutable **struct** with some properties:

```crystal
record Point, x y

point = Point.new(1, 2) 
point.x
point.y
point.x = 1 # undefined method "x="
```

So you can use them as tuples with names instead of `[0]`, `[1]` (in fact the macro was called `named_tuple` in the beginning).

I'll close this because it's a duplicate of #357

**Closed by asterite** 2015-08-06 13:50 UTC

**Comment by ozra** [comment] 2015-08-07 07:59
I should have learned by now to look out for macros ;-) Thanks
