### ISSUE TITLE
Strange behaviour when method called before is overriden (monkey patched)

### ISSUE THREAD

**Issue by radarek** [manastech/crystal#1625] opened 2015-09-28 11:09 UTC
```crystal
# puts "foo".size

class String
  def size
    0
  end
end

puts "bar".size
```

```
$ crystal mp.cr
0
```

But after uncommenting line no. 1 the result is different:

```
$ crystal mp.cr
3
3
```

Is it how it should work?

**Comment by jhass** [comment] 2015-09-28 11:41
Duplicate of #1104

**Closed by jhass** 2015-09-28 11:41 UTC
