### ISSUE TITLE
Define methods on an instance (Was: Defining a method on an instance crashes compiler)

### ISSUE THREAD

**Issue by jhass** [manastech/crystal#238] opened 2014-10-17 22:17 UTC
```ruby
class Foo
end

foo = Foo.new

def foo.bar
end
```

In Ruby we would call bar a singleton method. Every object in Ruby has a so called singleton class that sits at the actual root of the method lookup, basically each object instance is also a subclass of its type, although on the technical level it's closer to prepending an anonymous module to the ancestry chain (see Module#prepend). Using above syntax defines a method inside that class. To generally open an objects singleton class one uses:

```ruby
class << foo
  def bar
  end
end
```

In Ruby "class methods" are just singleton methods, they're defined on the current Class instance:

```ruby
class Foo
  self.is_a?(Class) #=> true

  # Four ways to define a "class method"
  def self.bar
  end

  class << self
    def bar
    end
  end

  def Foo.bar
  end

  class << Foo
    def bar
    end
  end
end
```

Currently this just crashes the compiler:

```
lookup_path_type not implemented for foo
*Exception#initialize<Exception, String, Nil>:Array(String) +21 [4464485]
*Exception::new<String>:Exception +125 [4464485]
*raise<String>:NoReturn +6 [4464485]
*Crystal::TypeVisitor#lookup_path_type<Crystal::TypeVisitor, Crystal::ASTNode+, Bool>:NoReturn +56 [4464485]
*Crystal::TypeVisitor#lookup_path_type<Crystal::TypeVisitor, Crystal::ASTNode+>:Crystal::Type+ +171 [4464485]
*Crystal::TypeVisitor#visit<Crystal::TypeVisitor, Crystal::Def+>:Bool +1070 [4464485]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +2122 [4464485]
*Crystal::Expressions#accept_children<Crystal::Expressions, Crystal::TypeVisitor>:Array(Crystal::ASTNode+) +104 [4464485]
*Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::TypeVisitor>:Nil +9723 [4464485]
*Crystal::Expressions#accept_children<Crystal::Expressions, Crystal::TypeVisitor>:Array(Crystal::ASTNode+) +104 [4464485]
*Crystal::Expressions@Crystal::ASTNode#accept<Crystal::Expressions, Crystal::TypeVisitor>:Nil +80 [4464485]
*Crystal::Program#infer_type<Crystal::Program, Crystal::Expressions>:Crystal::Expressions +32 [4464485]
*Crystal::Compiler#infer_type<Crystal::Compiler, Crystal::Program, Crystal::Expressions>:Crystal::Expressions +213 [4464485]
*Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +319 [4464485]
*Crystal::Command::run<Array(String)>:Nil +3349 [4464485]
*Crystal::Command::run:Nil +13 [4464485]
__crystal_main +5954 [4464485]
main +32 [4464485]
__libc_start_main +240 [4464485]
_start +41 [4464485]
 +41 [4464485]
```

**Comment by xdougx** [comment] 2015-09-08 15:27
`The problem is that it might slow down things at runtime` by @asterite 
Agreed, i was benchmarking some interactions with ln(x), Crystal can be 1000x faster then Ruby, looking for this feature now, is very convenient to have it, but i don't think to sacrifice this performance to have a very usual implementation, i think is possible to build in a different way this kind of implementation.

**Comment by asterite** [comment] 2015-09-30 14:14
I don't think we'll ever implement this, so I'm closing this for now.

**Closed by asterite** 2015-09-30 14:14 UTC
Labels: enhancement
