### ISSUE TITLE
compile error: cast to Crystal::ClassVarContainer failed when scope is VirtualType

### ISSUE THREAD

**Issue by luislavena** [manastech/crystal#1182] opened 2015-08-15 01:58 UTC
Hello,

Wasn't sure how to title this issue and still unsure if this describes the issue I'm hitting :smile: 

I've reached the following compiler crash:

```
cast to Crystal::ClassVarContainer failed
*Exception#initialize<Exception, String, Nil>:Array(String) +14 [4456698206]
*Exception::new<String>:Exception +89 [4456698153]
*raise<String>:NoReturn +6 [4456504902]
*Crystal::TypeVisitor#lookup_class_var<Crystal::TypeVisitor, Crystal::ClassVar, Bool>:Crystal::Var+ +787 [4466278451]
```

Since the backtrace is a *bit* long, I've managed to synthesize the problem to be a casting issue when accessing class variables of a VirtualType.

The following code triggers this issue. I have no doubt it could be further reduced for a test case, but I'm far beyond my level of experience with Crystal internals:

```crystal
abstract class Todo
  macro inherited
    @@items = [] of String
  end

  def list
    @@items
  end

  macro add(something)
    @@items << {{something}}
  end
end

class Home < Todo
  add "dishes"
  add "laundry"
end

class Work < Todo
  add "code"
  add "push"
  add "deploy"
end

todos = [
  Work.new,
  Home.new
]

# todos.class = Array(Todo+)
pp todos.class

todos.each do |todo|
  # HERE: compile error when class variable is accessed
  todo.list.each do |item|
  end
end
```

https://github.com/manastech/crystal/blob/master/src/compiler/crystal/semantic/type_inference.cr#L364

Please note that accessing the class variables is not an issue, it only turns into an issue when both are combined into an Array:

```crystal
# this compiles without issues
todo = Home.new
todo.list.each do |item|
  puts item
end
```

Hope all the above makes sense and helps figure out where the issue is coming from.

Thank you in advance.

:heart: :heart: :heart:

**Comment by asterite** [comment] 2015-08-15 02:04
Thanks for the detailed report!!

Yes, it's something that we didn't think about and must solve. In fact it's a duplicate of #916, so your title is a perfect description of the problem :-)

I'm actually glad that lately some bug reports are duplicates: it maybe means that we don't have many bugs but a few recurring ones. It also means we must fix them soon ;-)

**Closed by asterite** 2015-08-15 02:04 UTC

**Comment by luislavena** [comment] 2015-08-15 02:14
@asterite ohh GitHub-search-fu failed on me, which is why I submitted the bug report in the first place.

Thank you for the fast response!

Indeed having repeated bug reports is a good thing :smile:
