### ISSUE TITLE
Single line for variable typing and assignment

### ISSUE THREAD

**Issue by lepieru** [manastech/crystal#1906] opened 2015-11-25 16:32 UTC
When I want to type and assign a value to a variable `a`, I need two lines of code : 

``` ruby
a :: A
a = A.new
```

Could it be possible to allow a syntax like this one bellow ?

``` ruby
a :: A = A.new
```

**Comment by jhass** [comment] 2015-11-25 16:34
Duplicate of #919

**Closed by jhass** 2015-11-25 16:34 UTC

**Comment by omninonsense** [comment] 2015-11-25 17:08
Wouldn't say it's a duplicate; #919 is only related to integers.

Although, this is kind of redundant, because you can do

~~~crystal
a = A.new
~~~

Which is exactly what

~~~crystal
a :: A = A.new
~~~

would do anyway?

**Comment by asterite** [comment] 2015-11-25 17:09
@omninonsense Not quite, if you do:

```crystal
a = A.new
a = 1
```

then it works. With the type restriction the second line would be an error.

**Comment by omninonsense** [comment] 2015-11-25 17:11
@astetrite Ah, right; I get it now.

**Comment by jhass** [comment] 2015-11-25 17:28
To clarify, just because the example #919 uses integers, it doesn't make it only about integers.
