### ISSUE TITLE
Assertion failed: (isa(Val) && "cast() argument of incompatible type!

### ISSUE THREAD

**Issue by Perelandric** [manastech/crystal#1842] opened 2015-10-30 16:37 UTC
This code fails to compile and only gives the error below. I don't have any special flags set. Just compiling with `crystal test.cr`

```crystal
struct Foobar
    @value = "foobar"
end

def foo()
    _ = Foobar.new
end

foo()
```

>Assertion failed: (isa<X>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file /tmp/llvm20150726-78491-1dqz88o/llvm-3.6.2.src/include/llvm/Support/Casting.h, line 237.

It will succeed if I remove the `_ =` or if I throw any arbitrary expression on the line following the `_ = Foobar.new`.

>Crystal 0.9.1 (Fri Oct 30 16:14:17 UTC 2015)

**Comment by kirbyfan64** [comment] 2015-10-30 16:44
I think this is a regression, [it seems to work in 0.9.0](http://carc.in/#/r/l8t).

**Comment by Perelandric** [comment] 2015-10-30 16:51
@kirbyfan64 it doesn't show up in the playground but I've verified it in 0.9.0 as well

**Comment by asterite** [comment] 2015-10-30 16:53
Interesting, thanks for reporting :-)

What should be the return type and value of `foo`? `Foobar.new` is assigned to `_` so you are clearly not interested in its value, but should that value still "leak" and be the value of the method, or should we set it to `nil`?

/cc @jhass

**Comment by Perelandric** [comment] 2015-10-30 16:55
I would imagine `nil` would make sense. If one wanted to return the object, they'd drop the `_`.

 I use `_ =` as a way of reminding myself that I'm explicitly and knowingly ignoring a return value that I would normally utilize.

**Comment by asterite** [comment] 2015-10-30 16:58
Mmm... that's not idiomatic code at all, that just adds noise. We might eventually allow writing `def foo : Nil` or `def foo : Void` to make it clear the return value is of no interest, but generally you just don't do anything fancy about it (like in Ruby).

**Comment by Perelandric** [comment] 2015-10-30 16:59
@asterite Sorry, I forgot that I had a reduced example. 

In the real world code, `Foobar.new` is `obj.some_method`. So it's the `.some_method` return value that I'm ignoring.

**Comment by asterite** [comment] 2015-10-30 17:05
I'm not sure `_ = exp` is useful. If you want to return `nil` just do this:

```crystal
def foo
  obj.some_method
  nil
end
```

Or take a look at #1393

In fact I think I can make the formatter change `_ = exp` to just `exp` because it's just noise in the code.

**Comment by asterite** [comment] 2015-10-30 17:20
Well, I probably won't make the formatter change that because it'll be obtrusive, but I still find that expression kind of redundant.

**Comment by Perelandric** [comment] 2015-10-30 17:29
@asterite 

I think I'm not explaining myself very well. It doesn't have anything to do with the return value of `foo`. It has only to do with the fact that I'm ignoring the return value of `obj.some_method`.

Think of `obj.some_method` as something really important that returns a value that needs to be used 99% of the time. In that 1% when we need to call it but ignore the return value, I assign it to `_` in order to show that I'm ignoring it for a reason.

**Comment by asterite** [comment] 2015-10-30 17:44
So you do `_ = ...` for any expression you'd like to ignore the return value? Not assigning an expression to a variable is already ignoring the value... or not?

**Comment by Perelandric** [comment] 2015-10-30 17:48
@asterlite Yes, not assigning to a variable is already ignoring it. Assigning to `_` makes it explicitly clear that I'm intentionally discarding it and not just making a mistake. 

so to be clear, it seems  `_ = "any expression"` needs a return value, and `nil` would seem to make sense as a default but it ultimately doesn't matter to me. Only brought it up because of the error

**Comment by omninonsense** [comment] 2015-10-30 18:03
I see the usefulness of it, kinda.

Even though this is idiomatic in Go (and maybe other languages), it's not very idiomatic for Ruby (and thus Crystal) code. I'd actually prefer adding a comment `expression # ignored on purpose` rather than having a `_ = expression` because it looks strange (in the context of Ruby/Crystal).

I'll also admit that I'd go *what does this even mean* for a moment, if I came across it even if I'm familiar with that practice.

**Comment by Perelandric** [comment] 2015-10-30 18:16
@omninonsense Yeah, I'm not a Ruby developer. Since Crystal does have `_` for the purpose of discarding a value, it would seem necessary as an expression-based language to give it a value.

Code comments are useful too but if I need to search for discarded values, it can fail unless I'm perfectly consistent.

But I'm not on a mission here either. In that trailing position, I'm going to adopt `x! = _ = obj.some_method` or something. It's ugly but sufficient for this rare case.

**Comment by asterite** [comment] 2015-10-30 18:23
We introduced `_` to allow things such as:

```crystal
# I don't use the second value
x, _ = method_returning_two_values

# I don't use the first value
method_that_yields_two_values do |_, x|
end
```

Because of how the parser works, we also accidentally made `_ = exp` a possible expression, but in my opinion it doesn't make much sense. I never saw anyone writing Ruby code like that, and the few times I saw an underscore was in the cases I showed above.

I also don't quite understand how doing `_ = exp` is safer than just doing `exp`. Can you provide an example?

**Comment by jhass** [comment] 2015-10-30 18:27
I would argue to treat `_` as a regular variable, just don't warn or error on reassignments. That would mirror Ruby's behaviour and there's nothing really special to learn about it.

**Comment by Perelandric** [comment] 2015-10-30 18:28
@asterite 

It isn't safer; it's a visual indicator. Helps indicate to me that I didn't do something untoward while under the influence of beer and cold pizza.

**Closed** 2015-10-30 18:31 UTC
Labels: bug, compiler

**Comment by Perelandric** [comment] 2015-10-30 18:40
Thanks @asterite. I didn't realize the discardable `_ = expression` syntax wasn't intentional, so the questions about why I would use it were confusing. 

If it's now just a regular variable, I'd be satisfied using something else. I didn't need the underscore in particular. Just thought I was using it as intended.

**Comment by asterite** [comment] 2015-10-30 19:18
The `_` is not a regular variable: you can assign to it but not read it. In Ruby you can assign to it but read it, although I guess nobody reads it (except in `irb` it has the value of the last expression).

I fixed the bug, and the semantic of `_ = exp` is the same as before, only that the whole expression's type and value is that of `exp` (previously only the type was of exp, but the value was undefined, and that produces the crash).

**Comment by Perelandric** [comment] 2015-10-30 19:19
Understood. Thanks again.
