### ISSUE TITLE
String#split called with second parameter(limit) omits last empty string("") in Array.

### ISSUE THREAD

**Issue by arcage** [manastech/crystal#1930] opened 2015-12-07 00:53 UTC
```crystal
p "a,b,c,,,".split(',', 6) 
#=> ["a", "b", "c", "", ""]

p "a,b,c,,".split(',', 5)
#=> ["a", "b", "c", ""]

p "a,b,c,".split(',', 4)
#=> ["a", "b", "c"]
```

I think it isn't a normal function.

**Comment by asterite** [comment] 2015-12-07 01:36
Duplicate of #1070. I'll try to solve this issue with @waj this week, it's an important method that needs to work right.

**Closed by asterite** 2015-12-07 01:36 UTC
Labels: duplicate
