### ISSUE TITLE
Shards can't install repos with '.' in the name

### ISSUE THREAD

**Issue by sdogruyol** [manastech/crystal#1724] opened 2015-10-11 20:05 UTC
When trying to install with a shard.yml like below

```yaml
name: active-mysql
owner: Serdar Dogruyol
version: 0.1.0

dependencies:
  active_record.cr:
    github: waterlink/active_record.cr
```

I got an error like this

```
Updating https://github.com/waterlink/active_record.cr.git
Updating https://github.com/waterlink/mocks.cr.git
Unexpected event: NONE at 0:0 (YAML::ParseException)
[4341224130] *CallStack::unwind:Array(Pointer(Void)) +82
[4341224033] *CallStack#initialize<CallStack>:Array(Pointer(Void)) +17
[4341223992] *CallStack::new:CallStack +40
[4341268769] *Exception@Exception#initialize<YAML::ParseException, String>:CallStack +33
[4341268703] *YAML::ParseException#initialize<YAML::ParseException, String, UInt64, UInt64>:CallStack +143
[4341268529] *YAML::ParseException::new<String, UInt64, UInt64>:YAML::ParseException +129
[4341378141] *YAML::Parser#raise<YAML::Parser, String>:NoReturn +61
[4341378072] *YAML::Parser#unexpected_event<YAML::Parser>:NoReturn +88
[4341377371] *YAML::Parser#parse_node<YAML::Parser>:(Nil | String | Array(YAML::Type) | Hash(YAML::Type, YAML::Type)) +267
[4341377841] *YAML::Parser#parse_mapping<YAML::Parser>:Hash(YAML::Type, YAML::Type) +129
[4341377356] *YAML::Parser#parse_node<YAML::Parser>:(Nil | String | Array(YAML::Type) | Hash(YAML::Type, YAML::Type)) +252
[4341377029] *YAML::Parser#parse_document<YAML::Parser>:(Nil | String | Array(YAML::Type) | Hash(YAML::Type, YAML::Type)) +37
[4341376965] *YAML::Parser#parse<YAML::Parser>:(Nil | String | Array(YAML::Type) | Hash(YAML::Type, YAML::Type)) +101
[4341376609] *YAML::load<String>:(Nil | String | Array(YAML::Type) | Hash(YAML::Type, YAML::Type)) +33
[4341373197] *Shards::Spec::from_yaml<String>:Shards::Spec +29
[4341431758] *Shards::Resolver+@Shards::Resolver#spec<Shards::Resolver+, String>:Shards::Spec +78
[4341408298] *Shards::Package#spec<Shards::Package>:Shards::Spec +42
[4341397010] *Shards::Manager#resolve<Shards::Manager, Array(Shards::Dependency), Bool>:Array(Shards::Dependency) +130
[4341396869] *Shards::Manager#resolve<Shards::Manager, Shards::Spec>:Array(Shards::Dependency) +37
[4341397022] *Shards::Manager#resolve<Shards::Manager, Array(Shards::Dependency), Bool>:Array(Shards::Dependency) +142
[4341396869] *Shards::Manager#resolve<Shards::Manager, Shards::Spec>:Array(Shards::Dependency) +37
[4341396733] *Shards::Manager#resolve<Shards::Manager>:Array(Shards::Dependency)? +29
[4341441440] *Shards::Commands::Install#run<Shards::Commands::Install>:Array(Shards::Package)? +32
[4341372369] *Shards::Commands::install<String>:Array(Shards::Package)? +17
[4341372346] *Shards::Commands::install:Array(Shards::Package)? +26
[4341173622] ~fun_literal_29 +182
[4341447786] *OptionParser::ParseTask#parse<OptionParser::ParseTask>:Array(String)? +634
[4341363638] *OptionParser#parse<OptionParser, Array(String)>:Array(String)? +134
[4341159711] __crystal_main +27471
[4341168960] main +32
```

**Comment by waterlink** [comment] 2015-10-11 20:10
Have you tried this:

```yaml
dependencies:
  active_record:
    github: waterlink/active_record.cr
```

I am asking, because actual name of the library is `active_record`. And `.cr` is just a part of the name of the repo.

**Comment by sdogruyol** [comment] 2015-10-11 20:11
@waterlink let me check

**Comment by sdogruyol** [comment] 2015-10-11 20:12
Unfortunately i got the same error trace @waterlink

**Comment by waterlink** [comment] 2015-10-11 20:21
I wonder, if it has anything to do with `active_record.cr` not yet having `shards.yml`. Let me try adding it.

**Comment by waterlink** [comment] 2015-10-11 20:30
I have pushed proper `shard.yml`. Can you try again?

**Comment by waterlink** [comment] 2015-10-11 22:30
For me provided `shard.yml` snippet works now :)

**Comment by jhass** [comment] 2015-10-12 09:03
Besides currently issues for shards should go to http://github.com/ysbaddaden/shards

**Comment by ysbaddaden** [comment] 2015-10-12 09:03
Shards does its best to generate a `shard.yml` when its missing, parsing deps from the Projectile. I think it failed to generate correct dependencies for `mocks.cr`, which you fixed by having a correct `shard.yml`. I guess the `.` is indeed the cause.

**Closed by jhass** 2015-10-12 09:03 UTC
Labels: question

**Comment by alex-fedorov** [comment] 2015-10-12 10:11
I think the cause is `name (from src dir)` != `name (from git repo)` + absence of `shard.yml` to clarify the difference.
