### ISSUE TITLE
Nil assertion failed when trying to compile a benchmark

### ISSUE THREAD

**Issue by lucaong** [manastech/crystal#2058] opened 2016-01-24 18:19 UTC
Hey, I think I hit a compiler bug in `0.11.0` 😁
Trying to use a variable created outside the block in a benchmark `report` block causes the compilation to fail with a `Nil assertion failed`.

## OS and compiler version:

```
Crystal 0.11.0 (Sat Jan 23 19:17:27 UTC 2016)
Mac OSX 10.11.2
```

## Minimal code to reproduce the issue:

```ruby
require "benchmark"

x = 42

Benchmark.bm do |bm|
  bm.report("crash") do
    x
  end
end
```

## Error output:

```
Nil assertion failed
[4322117499] *raise<String>:NoReturn +139
[4322322192] *Nil#not_nil!<Nil>:NoReturn +16
[4325711579] *Crystal::CodeGenVisitor#codegen_fun<Crystal::CodeGenVisitor, String, Crystal::Def, Crystal::Type+, Bool, LLVM::Module, Bool, Bool>:LLVM::Function +3355
[4325659304] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +4632
[4325762271] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +559
[4325656032] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1360
[4325664556] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +9884
[4325657246] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +2574
[4325764751] *Crystal::CodeGenVisitor#visit<Crystal::CodeGenVisitor, Crystal::Call>:Bool +3039
[4325656032] *Crystal::ASTNode+@Crystal::ASTNode#accept<Crystal::ASTNode+, Crystal::CodeGenVisitor>:Nil +1360
[4325480492] *Crystal::Compiler#codegen<Crystal::Compiler, Crystal::Program, Crystal::Expressions, Array(Crystal::Compiler::Source), String>:Nil +3036
[4324490358] *Crystal::Compiler#compile<Crystal::Compiler, Array(Crystal::Compiler::Source), String>:Crystal::Compiler::Result +4726
[4328934465] *Crystal::Command#run_command<Crystal::Command>:Nil +145
[4328752240] *Crystal::Command#run<Crystal::Command>:(Nil | Bool | Array(String) | IO::FileDescriptor+ | Crystal::Compiler::Result | Array(Crystal::ImplementationTrace) | Array(Crystal::Init::View+:Class)) +9120
[4328741986] main +24402
```

Also the example about the `Benchmark.bm` method in the API documentation does not compile for the same reason.

I hope this helps,
Keep up with the great work :)

**Comment by sdogruyol** [comment] 2016-01-24 18:45
I'm also having the same error with `spawn`. This works on `0.10.2`

```crystal
channel = Channel(String).new
spawn {
  channel.send "Naber"
}
puts channel.receive
```

**Comment by asterite** [comment] 2016-01-24 19:23
Yes, duplicate of #2050. We'll make a release soon, either with these bug fixes or maybe with a couple more things.

**Closed** 2016-01-24 19:23 UTC
