### ISSUE TITLE
Bug in compiler

### ISSUE THREAD

**Issue by waterlink** [manastech/crystal#500] opened 2015-03-23 18:41 UTC
Don't know why this happened, but log is here: https://gist.github.com/waterlink/d903216aaca5df8ccaa1

**Comment by jhass** [comment] 2015-03-23 20:22
Any chance you could try to reduce your code to something that you can post here and that still reproduces the issue?

**Comment by waterlink** [comment] 2015-03-23 20:39
Can't really reproduce it on my home linux box. The log is from mac os x laptop, I will try tomorrow when I get to it.

**Comment by waterlink** [comment] 2015-03-23 20:43
Related code was:

```ruby
    VALUE_DOWN_DISPATCH = {
      Int => Integer,
      ::Float => Float,
    }

   # ...

   VALUE_DOWN_DISPATCH.fetch(value.class) { Value }.new(value, field)
```

where `Value`, `Integer < Value`, `Float < Value` are my classes (structs actually).

**Comment by waterlink** [comment] 2015-03-24 21:00
The thing I tried to do is wrong in its roots, because I try to fetch exact type, but what I actually wanted is to fetch exact type or any of its superclasses, which I can't find possible to do in this way. I have fallen back to this: https://github.com/waterlink/crystal-mysql/blob/2b40960f886fe5afbaee6cd73a15970a80752b4f/src/mysql/types.cr#L37-L41 instead of using hash constant for dispatching. This looks way better.

**Comment by asterite** [comment] 2015-03-25 20:30
@waterlink If you could reproduce it somehow and send some code that reproduces the bug (be it the source code itself or some git revision of one of your projects), I'll be able to reduce it and find it. Thanks!

**Comment by waterlink** [comment] 2015-03-30 17:10
@asterite I was able to reproduce this bug in pretty small example: https://github.com/waterlink/crystal-issue-500

**Comment by asterite** [comment] 2015-03-30 17:15
@waterlink  Excellent, thank you!! I'll debug it and fix it soon :-)

**Comment by waterlink** [comment] 2016-02-20 23:52
@asterite Any news on this one? Is it still a thing? Should we close it?

**Comment by asterite** [comment] 2016-02-21 15:50
@waterlink It seems to be working now, so I guess we can close it :-)

**Closed by asterite** 2016-02-21 15:50 UTC
Labels: bug, compiler
