### ISSUE TITLE
Return type of lambda expression seems to be incorrect.

### ISSUE THREAD

**Issue by rhysd** [manastech/crystal#653] opened 2015-05-12 13:53 UTC
Return type of lambda expression seems to be incorrect.

```ruby
p -> (args : Array(Int32)) {
  return args[0]
}
#=> #<(Array(Int32) -> NoReturn):0x108F24750>
```

I expected `Array(Int32) -> Int32`.  When I omitted `return` in body of lambda expression, the result was not changed.
Do I have any mistakes or is it a bug of compiler?

- Environment
  - Crystal 0.7.1
  - OS X 10.9

**Comment by rhysd** [comment] 2015-05-12 13:56
Note that below shows correct result `1`.

```ruby
p -> (args : Array(Int32)) {
  return args[0]
}.call([1, 2, 3])
```

**Comment by asterite** [comment] 2015-05-12 15:09
Since an `Array(Int32)` was never instantiated in the first program, the compiler doesn't know the type of `args[0]`. For these cases, the compiler just concludes that `args[0]` is `NoReturn`, since that line can never be reached (if you never instantiated an `Array(Int32)`, you can never invoke that lambda). So the compiler is right, although it's not very intuitive. 

Note that if you instantiate an `Array(Int32)` before or after that line, it works fine.

Is this affecting your code in some way?

**Comment by rhysd** [comment] 2015-05-12 16:48
@asterite 

Oh, I got it!

Crystal's template instantiation is lazier than I thought.   I supposed that `Array(Int32)` was instantiated when the argument `args` was defined.

I'm implementing Lisp in Crystal and [here](https://github.com/rhysd/mal/blob/crystal/crystal/step4_if_fn_do.cr#L14) causes this issue.  Conversion by `as Mal::Func` failed at runtime because of `NoReturn`.  However, the problem was resolved when the return value of `func_of()` is used as you said.

I think it was an edge case and it doesn't worse paying cost of extra template instantiation.

**Comment by asterite** [comment] 2015-05-12 17:04
@rhysd So cool! You are writing a mal interpreter :-)

I also did that exercise, it was really good. I think I missed the last two points or so.

I have to tell you, when I was doing it I uncovered a lot of bugs in Crystal so it wouldn't surprise me at all if you found more bugs.

Yes, method instantiation is very lazy :-) We could try to instantiate `Array(Int32)` in that proc if it has an argless `new`, I guess, and deduce the types from there. But if the type doesn't provide an argless `new` that won't work, so that's going to be an inconsistency (and we don't like them).

**Comment by rhysd** [comment] 2015-05-13 07:31
@asterite 

Thanks! :dog:

> I have to tell you, when I was doing it I uncovered a lot of bugs in Crystal so it wouldn't surprise me at all if you found more bugs.

No problem. I understand that Crystal is in pre-alpha phase.

> Yes, method instantiation is very lazy :-) We could try to instantiate Array(Int32) in that proc if it has an argless new, I guess, and deduce the types from there. But if the type doesn't provide an argless new that won't work, so that's going to be an inconsistency (and we don't like them).

At least user can't know where `NoReturn` comes from.  So I think at least compiler should output the warning (e.g. `Array(Int32)` is specified but never instantiated).  Although it is better that a compiler instantiates `Array(Int32)` when it is used in parameter of lambda, it needs to pay cost to instantiate the type which may not be used (I don't know how much cost a compiler pays to instantiate a type).

**Comment by jhass** [comment] 2015-08-31 22:38
I'd say this sounds like won't fix/works as intended? Do we maybe need to turn this into a doc bug?

**Comment by asterite** [comment] 2015-09-30 14:42
I'll close this. It works as intended, it might just not be very intuitive (specially the NoReturn thing).

**Closed by asterite** 2015-09-30 14:42 UTC

**Comment by rhysd** [comment] 2015-09-30 15:39
:+1:
