### ISSUE TITLE
ctags

### ISSUE THREAD

**Issue by k2b6s9j** [manastech/crystal#577] opened 2015-04-25 22:56 UTC
Anyway I get a ctags file for a project so far? I was looking around to see if there was a LLVM generic way to pull it off, but all of the 'LLVM' solutions are based in clang.

**Comment by asterite** [comment] 2015-04-26 00:05
Maybe you could probably reuse some ctags code from Ruby.

**Comment by datanoise** [comment] 2015-04-27 14:18
If you are looking for the crystal code ctags, I'm using the following script:

https://gist.github.com/datanoise/c3e3465029009f55a6e4

it doesn't have etags style implemented yet though.

**Comment by k2b6s9j** [comment] 2015-04-28 02:23
So, @asterite, any chance we could get this kind of feature integrated into the compiler in the next version?

**Comment by asterite** [comment] 2015-04-28 13:08
I don't think generating ctags is the compiler's job. Or maybe yes? We could have something like `crystal tools ctags`, I don't know.

In any case, I wrote this for fun, to see how hard it would be reusing the compiler's code, and it seems to work. I don't know much about ctags, but I tried it with the SublimeText plugin:

```crystal
require "compiler/crystal/**"

include Crystal

class CTagsVisitor < Visitor
  record Tag, name, filename, regex, kind

  getter tags

  def initialize(@base_dir)
    @files_to_lines = {} of String => Array(String)
    @tags = [] of Tag
  end

  def process(filename)
    contents = File.read(filename)
    @files_to_lines[filename] = contents.lines

    parser = Parser.new contents
    parser.filename = filename
    parser.parse.accept self
  end

  def visit(node : ClassDef)
    process_node node, node.name.names.last, "c"
    true
  end

  def visit(node : ModuleDef)
    process_node node, node.name.names.last, "m"
    true
  end

  def visit(node : Def)
    process_node node, node.name, "d"
    false
  end

  def visit(node : Macro)
    process_node node, node.name, "x"
    true
  end

  def visit(node : LibDef)
    process_node node, node.name, "l"
    true
  end

  def visit(node : StructOrUnionDef)
    process_node node, node.name, "s"
    true
  end

  def visit(node : FunDef)
    process_node node, node.name, "l"
    true
  end

  def visit(node : Expressions)
    true
  end

  def visit(node : ASTNode)
    true
  end

  def process_node(node, name, kind)
    location = node.location
    return true unless location

    filename = location.filename
    return true unless filename.is_a?(String)

    line = @files_to_lines[filename][location.line_number - 1]
    regex = escape_regex(line)

    @tags << Tag.new(name, relativize(filename), regex, kind)
    true
  end

  def relativize(filename)
    if filename.starts_with?(@base_dir)
      filename = filename[@base_dir.length .. -1]
      filename = filename[1 .. -1] if filename.starts_with? '/'
      filename
    else
      filename
    end
  end

  REPLACEMENTS = {
    "(": "\\(",
    ")": "\\)",
    "[": "\\[",
    "]": "\\]",
    "{": "\\{",
    "}": "\\}",
  }

  def escape_regex(string)
    string.gsub(/\(\)\[\]\{\}/, REPLACEMENTS)
  end
end

visitor = CTagsVisitor.new(Dir.working_directory)

# Apparently Dir.glob("**/*.cr") doesn't work like Ruby :-(
Dir.glob("*.cr", "**/*.cr", "**/**/*.cr", "**/**/**/*.cr", "**/**/**/**/*.cr") do |file|
  visitor.process File.expand_path(file)
end
tags = visitor.tags
tags.sort_by! &.name

File.open(".tags", "w") do |file|
  BufferedIO.new(file) do |io|
    io.puts %(!_TAG_FILE_FORMAT 2 /extended format; --format=1 will not append ;" to lines/)
    io.puts %(!_TAG_FILE_SORTED 1 /0=unsorted, 1=sorted, 2=foldcase/)
    tags.each do |tag|
      io << tag.name << "\t" << tag.filename << "\t/^" << tag.regex << "$/;\"\t" << tag.kind
      io.puts
    end
  end
end
```

It probably needs some enhancements, I don't know much about ctags.

**Comment by asterite** [comment] 2015-04-28 14:33
@datanoise Sorry! I must have missed your comment/email, @waj just let me know that you basically did the same thing as me. My "solution" is in no way better than yours, in fact it's probably worse because I know nothing about ctags (like, I can see some scope-related stuff in your code). I'm actually really surprised that you manage to use the compiler's API without any documentation at all! Amazing!

**Comment by datanoise** [comment] 2015-04-28 15:05
@asterite No problem at all. Now we have two solutions when there were none :). And you are right, having a scope related tag information is nice for plugins like vim's tagbar or ctrlp, so choose whichever better fits you.

**Comment by jhass** [comment] 2015-10-18 12:11
I think the question is answered and I'm not sure what the issue is supposed to track anymore, closing.

**Closed by jhass** 2015-10-18 12:11 UTC
Labels: question

**Comment by TheLonelyGhost** [comment] 2017-01-24 18:23
Since this issue appears to recur every few months (#2768)...

There is now a tool for vim-style `ctags` (not yet emacs, but pull requests are welcome) by parsing the crystal AST, thanks to @asterite's example code above. See https://github.com/thelonelyghost/crystal-ctags for more.

If this is used enough, perhaps it might merit being merged as part of `crystal tool`, but not right now.
