### ISSUE TITLE
Compiler crash on Ubuntu 14.04/amd64

### ISSUE THREAD

**Issue by js-ojus** [manastech/crystal#1403] opened 2015-09-07 07:02 UTC
### When?

When trying to compile a Ruby source file as Crystal source.

### What is in the source file?

It is the Ruby version of `binarytrees.rb` at http://benchmarksgame.alioth.debian.org.

### What is expected?

Successful compilation, either with or without errors.

### What is observed?

Crystal compiler crashed with a segmentation fault.

```bash
js@karta:~/tmp/lang/crystal/a > crystal build src/a.cr
/usr/bin/crystal: line 6:  5518 Segmentation fault      "$INSTALL_DIR/embedded/bin/crystal" "$@"
js@karta:~/tmp/lang/crystal/a > crystal build --release src/a.cr
/usr/bin/crystal: line 6:  5532 Segmentation fault      "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

### System details

```bash
js@karta:~/tmp/lang/crystal/a > uname -a
Linux karta 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

js@karta:~/tmp/lang/crystal/a > crystal -v
Crystal 0.7.7 [170f859] (Sat Sep  5 03:00:48 UTC 2015)
```

Please let me know if I can extract any more useful information.

**Comment by asterite** [comment] 2015-09-07 22:21
This is a duplicate of #795, which is a duplicate of #793

**Closed by asterite** 2015-09-07 22:21 UTC
Labels: bug, compiler
