### ISSUE TITLE
Make nil tracing a little bit smarter

### ISSUE THREAD

**Issue by pgkos** [manastech/crystal#1561] opened 2015-09-22 15:55 UTC
This works:
```crystal
a = 5 as Int32?
b = 4 as Int32?

if a && b
  puts a * b
else
end
```
but this does not:
```crystal
a = 5 as Int32?
b = 4 as Int32?

if !a || !b
else
  puts a * b
end
```
Also, it would be nice if this also worked:
```crystal
if a != nil && b != nil  # explicit checking for nil
  puts a * b  # compiler complains that a or b still could be nil
else
end
```

**Comment by jhass** [comment] 2015-09-22 15:58
Are you okay with closing this as a duplicate of #1196 ?

**Comment by asterite** [comment] 2015-09-22 16:25
This is definitely a duplicate

**Closed by asterite** 2015-09-22 16:25 UTC
