### ISSUE TITLE
building with crystal with --debug errors out

### ISSUE THREAD

**Issue by weskinner** [manastech/crystal#397] opened 2015-02-05 01:52 UTC
```
vagrant@vagrant-ubuntu-trusty-64:~/crystal$ ./bin/crystal build --debug src/compiler/crystal.cr 
Using compiled compiler at .build/crystal
.crystal//home/vagrant/crystal/src/compiler/crystal.cr/main.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc -o crystal .crystal//home/vagrant/crystal/src/compiler/crystal.cr/main.o .crystal//home/vagrant/crystal/src/compiler/crystal.cr/
...
```

**Comment by asterite** [comment] 2015-02-05 12:35
Duplicate of #257

For now we have to use the old `puts` debugging style.

**Closed** 2015-02-05 12:35 UTC
Labels: bug
