### ISSUE TITLE
Segmentation fault on recursive yielding

### ISSUE THREAD

**Issue by sergey-kucher** [manastech/crystal#1178] opened 2015-08-14 16:55 UTC
```crystal
def foo(n)
  return if n > 5
  yield "foo #{n}"

  foo(n + 1) do
    puts "nesting..."
  end
end

foo(1) do |a|
  puts a
end
```
This gives
```
/usr/bin/crystal: line 6: 15377 Segmentation fault      "$INSTALL_DIR/embedded/bin/crystal" "$@"
```

**Comment by sergey-kucher** [comment] 2015-08-14 16:58
I think this certainly because of inline implementation of blocks. But I think compiler should provide readable error message.

**Comment by asterite** [comment] 2015-08-14 16:59
Yes, that's the reason. It's a duplicate of #538

**Closed by asterite** 2015-08-14 16:59 UTC
