### ISSUE TITLE
Annoying warning about tempnam

### ISSUE THREAD

**Issue by stugol** [manastech/crystal#2091] opened 2016-01-31 20:26 UTC
```
In function `__crystal_main':
main_module:(.text+0xbaac): warning: the use of `tempnam' is dangerous, better use `mkstemp'
```
Wtf? I don't want to use `mkstemp`, because I want to create a _directory_, not a file. I also don't want my executable to spit out stupid warnings every time I run it.

**Comment by ysbaddaden** [comment] 2016-01-31 20:42
Please mind your language.

This looks like a LLVM or CC warning (Crystal prints no warning). You should take it more seriously and follow the advice of a compiler reporting a _dangerous_ call.

**Comment by asterite** [comment] 2016-01-31 20:53
Closing as wontfix, since @stugol is using bad language ("stupid", "annoying", "wtf"). Please create another issue with proper language if you want to get any reply from no on.

**Closed by asterite** 2016-01-31 20:53 UTC
Labels: wontfix

**Comment by marceloboeira** [comment] 2016-01-31 21:06
@asterite 👏🏼

**Comment by stugol** [comment] 2016-02-01 04:01
"annoying" is bad language? Jeez you're touchy. And behaving like a child. "I don't like these warnings being called stupid, even though _they're nothing to do with me_, so I'm closing this and issuing an ultimatum"

If I were hurling abuse, you'd have a point. But innocent expressions like "wtf"? Don't be absurd.

**Comment by stugol** [comment] 2016-02-01 04:03
@ysbaddaden: How can I follow the advice of the compiler, when the compiler is advising I use a completely different function that performs a different task that is not applicable to my use case?

**Comment by ysbaddaden** [comment] 2016-02-01 07:37
1. https://github.com/manastech/crystal/blob/master/CODE_OF_CONDUCT.md
2. Ask the gurus on stackoverflow.

**Comment by stugol** [comment] 2016-02-01 12:48
@ysbaddaden: Which part of that document would you say prohibits the use of the expression "wtf", outlaws referring to anything as "annoying", and similarly forbids the categorisation of linker warnings as "stupid"?

@marceloboeira if you have the clap go see the doctor.

**Comment by asterite** [comment] 2016-02-01 13:33
@stugol There's also point 3: common sense. Calling a warning "annoying", saying that something is "stupid" or saying "wtf" adds nothing to the bug report. Absolutely nothing. Worse, it can be considered as offensive, as I'll show below.

```
@stugol The text in your bug reports is annoying and stupid, wtf?.
```

I'm not saying you are stupid or what you do is annoying, it's just the text you wrote. But don't you think that if I say that, since you wrote those words you might apply those "stupid" and "annoying" adjectives to yourself? Well, that's how we could also understand it, so you are effectively calling the maintainers of the language stupid and annoying.

(but then while also asking about the code of conduct you kind of insluted @marceloboeira, which, again, adds nothing to the discussion, and goes against the code of conduct)

Here's a better bug report:

```
When compiling this program in Ubuntu Trusty 64 bits:

(some code)

I'm getting this:

In function `__crystal_main':
main_module:(.text+0xbaac): warning: the use of `tempnam' is dangerous, better use `mkstemp'

(An possible questions for the above)
1. Why I'm getting that error?
2. How can I/we fix this?
3. Is anyone else getting that? Am I doing something wrong?
4. Should we maybe use another C function for this?
```

Note that in your bug report you didn't provide your machine specifications, you didn't provide code to reproduce it, but instead you just complained about the compiler's behaviour. There's no need to complain, we are doing this for free and nobody is forcing you to use this language.

**Comment by stugol** [comment] 2016-02-01 18:19
@asterite I see your point. I will endeavour to be less judgemental in my reports in future.
