### ISSUE TITLE
Error executing web frameworks

### ISSUE THREAD

**Issue by Vikaton** [manastech/crystal#611] opened 2015-05-02 15:23 UTC
I fired up a new Debian 7 box, installed crystal 0.7.1, git cloned Frank(and amatista(I tried crystal deps on that, and same error)) and tried to execute the examples programs

--single-module version
```
Error: execution of command failed with code: 1: `cc -o /tmp/crystal-run-hello_world.wX5zt8 .crystal//root/Frank/samples/hello_world.cr/main.o   -lssl -lcrypto -levent -
lrt -lpcl -lpcre -lgc -lpthread -lunwind`
```

This is the error I got :(

```
cc: error: .crystal//root/Frank/samples/hello_world.cr/OptionParser5858Exception43.o: No such file or directory                                                          
cc: error: .crystal//root/Frank/samples/hello_world.cr/GlobError.o: No such file or directory                                                                            
cc: error: .crystal//root/Frank/samples/hello_world.cr/IO5858EOFError.o: No such file or directory                                                                       
Error: execution of command failed with code: 1: `cc -o /tmp/crystal-run-hello_world.cH7GDi .crystal//root/Frank/samples/hello_world.cr/main.o .crystal//root/Frank/sampl
es/hello_world.cr/CFileIO.o .crystal//root/Frank/samples/hello_world.cr/Array40Int3241.o .crystal//root/Frank/samples/hello_world.cr/Math.o .crystal//root/Frank/samples/
hello_world.cr/Pointer40Int3241.o .crystal//root/Frank/samples/hello_world.cr/ArgumentError.o .crystal//root/Frank/samples/hello_world.cr/Pointer40UInt841.o .crystal//ro
ot/Frank/samples/hello_world.cr/Pointer40LibABI5858UnwindException41.o .crystal//root/Frank/samples/hello_world.cr/UInt64.o .crystal//root/Frank/samples/hello_world.cr/A
rray40String41.o .crystal//root/Frank/samples/hello_world.cr/Pointer40String41.o .crystal//root/Frank/samples/hello_world.cr/GC.o .crystal//root/Frank/samples/hello_worl
d.cr/String.o .crystal//root/Frank/samples/hello_world.cr/String5858Builder.o .crystal//root/Frank/samples/hello_world.cr/Slice40T41.o .crystal//root/Frank/samples/hello
_world.cr/Slice40UInt841.o .crystal//root/Frank/samples/hello_world.cr/IndexOutOfBounds.o .crystal//root/Frank/samples/hello_world.cr/DivisionByZero.o .crystal//root/Fra
nk/samples/hello_world.cr/StaticArray40UInt844322241.o .crystal//root/Frank/samples/hello_world.cr/Exception.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Point
er40UInt84141.o .crystal//root/Frank/samples/hello_world.cr/Slice40Pointer40UInt84141.o .crystal//root/Frank/samples/hello_world.cr/Array40Pointer40Void4141.o .crystal//
root/Frank/samples/hello_world.cr/Pointer40Pointer40Void4141.o .crystal//root/Frank/samples/hello_world.cr/Fiber.o .crystal//root/Frank/samples/hello_world.cr/Pointer40V
oid41.o .crystal//root/Frank/samples/hello_world.cr/Array40Fiber41.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Fiber41.o .crystal//root/Frank/samples/hello_wo
rld.cr/Event5858Base.o .crystal//root/Frank/samples/hello_world.cr/Scheduler.o .crystal//root/Frank/samples/hello_world.cr/Frank5858Config.o .crystal//root/Frank/samples
/hello_world.cr/Hash40Char4432String41.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Hash40K4-3fe342251119048dfe8840eed40c12f3.o .crystal//root/Frank/samples/he
llo_world.cr/Hash40K4432V415858Entry40Char4432String41.o .crystal//root/Frank/samples/hello_world.cr/Hash40K4432V415858StandardComparator.o .crystal//root/Frank/samples/
hello_world.cr/Char.o .crystal//root/Frank/samples/hello_world.cr/Int32.o .crystal//root/Frank/samples/hello_world.cr/Frank5858Handler.o .crystal//root/Frank/samples/hel
lo_world.cr/Array40Frank5858Route41.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Frank5858Route41.o .crystal//root/Frank/samples/hello_world.cr/AtExitHandlers.
o .crystal//root/Frank/samples/hello_world.cr/Array404032456232Void4141.o .crystal//root/Frank/samples/hello_world.cr/Pointer404032456232Void4141.o .crystal//root/Frank/
samples/hello_world.cr/OptionParser.o .crystal//root/Frank/samples/hello_world.cr/Array40OptionParser5858Handler41.o .crystal//root/Frank/samples/hello_world.cr/Pointer4
0OptionParser5858Handler41.o .crystal//root/Frank/samples/hello_world.cr/OptionParser5858Handler.o .crystal//root/Frank/samples/hello_world.cr/Frank.o .crystal//root/Fra
nk/samples/hello_world.cr/OptionParser5858ParseTask.o .crystal//root/Frank/samples/hello_world.cr/Regex.o .crystal//root/Frank/samples/hello_world.cr/StaticArray40UInt84
4321241.o .crystal//root/Frank/samples/hello_world.cr/CharReader.o .crystal//root/Frank/samples/hello_world.cr/InvalidByteSequenceError.o .crystal//root/Frank/samples/he
llo_world.cr/Bool.o .crystal//root/Frank/samples/hello_world.cr/MatchData.o .crystal//root/Frank/samples/hello_world.cr/Nil.o .crystal//root/Frank/samples/hello_world.cr
/OptionParser5858MissingOption.o .crystal//root/Frank/samples/hello_world.cr/Range40B4432E41.o .crystal//root/Frank/samples/hello_world.cr/Range40Int324432Int3241.o .cry
stal//root/Frank/samples/hello_world.cr/OptionParser5858InvalidOption.o .crystal//root/Frank/samples/hello_world.cr/Array40HTTP5858Handler4341.o .crystal//root/Frank/sam
ples/hello_world.cr/Pointer40HTTP5858Handler4341.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858LogHandler.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858S
taticFileHandler.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858Server.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858Handler43.o .crystal//root/Frank/samp
les/hello_world.cr/StaticArray40UInt84432441.o .crystal//root/Frank/samples/hello_world.cr/TCPServer.o .crystal//root/Frank/samples/hello_world.cr/PointerIO.o .crystal//
root/Frank/samples/hello_world.cr/SocketError.o .crystal//root/Frank/samples/hello_world.cr/UInt16.o .crystal//root/Frank/samples/hello_world.cr/Errno.o .crystal//root/F
rank/samples/hello_world.cr/LibEvent25858EventFlags.o .crystal//root/Frank/samples/hello_world.cr/FileDescriptorIO.o .crystal//root/Frank/samples/hello_world.cr/IO5858Er
ror.o .crystal//root/Frank/samples/hello_world.cr/BufferedIO40T41.o .crystal//root/Frank/samples/hello_world.cr/BufferedIO40TCPSocket4341.o .crystal//root/Frank/samples/
hello_world.cr/StaticArray40UInt844321638441.o .crystal//root/Frank/samples/hello_world.cr/StringIO.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858Request.o .crys
tal//root/Frank/samples/hello_world.cr/TCPSocket43.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858Headers.o .crystal//root/Frank/samples/hello_world.cr/Hash40Stri
ng4432Array40String4141.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Hash40K4-4e22cbfaaeaaecc0f6b9a2d2252636f6.o .crystal//root/Frank/samples/hello_world.cr/Ha
sh40K4432V41585-6ae11b6ee1fda3db47c9c3f0fe007f56.o .crystal//root/Frank/samples/hello_world.cr/HTTP.o .crystal//root/Frank/samples/hello_world.cr/PointerAppender40T41.o 
.crystal//root/Frank/samples/hello_world.cr/PointerAppender40UInt841.o .crystal//root/Frank/samples/hello_world.cr/Frank5858Route.o .crystal//root/Frank/samples/hello_wo
rld.cr/Hash40String4432String41.o .crystal//root/Frank/samples/hello_world.cr/Pointer40Hash40K4-94b13ddffb23529372d461c0c2add2fe.o .crystal//root/Frank/samples/hello_wor
ld.cr/Hash40K4432V415858Entry40String4432String41.o .crystal//root/Frank/samples/hello_world.cr/Frank5858Request.o .crystal//root/Frank/samples/hello_world.cr/Frank5858C
ontext.o .crystal//root/Frank/samples/hello_world.cr/HTTP5858Response.o .crystal//root/Frank/samples/hello_world.cr/Exception43.o .crystal//root/Frank/samples/hello_worl
d.cr/Dir.o .crystal//root/Frank/samples/hello_world.cr/File5858Stat.o .crystal//root/Frank/samples/hello_world.cr/HTML5858Builder.o .crystal//root/Frank/samples/hello_wo
rld.cr/HTML.o .crystal//root/Frank/samples/hello_world.cr/StaticArray40UInt8443225641.o .crystal//root/Frank/samples/hello_world.cr/Hash40Symbol4432String41.o .crystal//
root/Frank/samples/hello_world.cr/Pointer40Hash40K4-0e39f657309f762225eca8508214b53b.o .crystal//root/Frank/samples/hello_world.cr/Hash40K4432V415858Entry40Symbol4432Str
ing41.o .crystal//root/Frank/samples/hello_world.cr/Symbol.o .crystal//root/Frank/samples/hello_world.cr/File.o .crystal//root/Frank/samples/hello_world.cr/TCPSocket.o .
crystal//root/Frank/samples/hello_world.cr/LEBReader.o .crystal//root/Frank/samples/hello_world.cr/Base645858Error.o .crystal//root/Frank/samples/hello_world.cr/OptionPa
rser5858Exception43.o .crystal//root/Frank/samples/hello_world.cr/GlobError.o .crystal//root/Frank/samples/hello_world.cr/IO5858EOFError.o .crystal//root/Frank/samples/h
ello_world.cr/IO5858Error43.o .crystal//root/Frank/samples/hello_world.cr/TimeFormat5858Error.o .crystal//root/Frank/samples/hello_world.cr/MissingKey.o .crystal//root/F
```

Any solutions?

**Comment by jhass** [comment] 2015-05-02 16:49
I can't reproduce your issue: https://asciinema.org/a/19462

**Comment by asterite** [comment] 2015-05-02 16:52
Me neither. Can you check that the files that `cc` can't find don't really exist? Also, can you try replacing the `//` with single slashes in the command line and see if that works? (I think it makes no difference, but just in case...)

**Comment by Vikaton** [comment] 2015-05-02 17:26
http://prntscr.com/70plgj

Thats what I get executing the command itself, and a `ld -lpcl` shows not found either :/

**Comment by Vikaton** [comment] 2015-05-02 23:05
Could RAM be an issue? http://prntscr.com/70uaen

**Comment by dhruvrajvanshi** [comment] 2015-05-03 13:42
I have a similar issue. In ubuntu(14.10 in virtualbox), executing any program which requires "http" resulted in an error that looked like that.
OP, can you try running a file with a single line to check if our issues are same
```
require "http"
```

**Comment by Vikaton** [comment] 2015-05-03 14:11
Yup ^, got the a very similar error from the one I reported.

@dhruvrajvanshi how much RAM does your virtual box have?

**Comment by dhruvrajvanshi** [comment] 2015-05-03 15:35
2 GB

**Comment by Vikaton** [comment] 2015-05-03 16:15
ah, then it might not be a RAM issue after all :/

**Comment by asterite** [comment] 2015-06-16 17:53
@Vikaton Did you figure what was the problem?

**Comment by Vikaton** [comment] 2015-06-16 17:55
I did not, because I got a new box and it worked just fine, I think it may be just a memory issue

**Comment by asterite** [comment] 2015-06-16 19:01
Good. I'll close this for now (because we couldn't reproduce it).

**Closed by asterite** 2015-06-16 19:01 UTC
