### ISSUE TITLE
String.split different from ruby and possible bug

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1197] opened 2015-08-16 23:06 UTC
ruby:
```
"a=".split("=", 2)
=> ["a", ""]
```

crystal:
```
"a=".split("=", 2)
=> ["a"]
```

 I believe the crystal result is incorrect since the delimiter exists.  The 2nd value should be a blank string.  Otherwise it is impossible to differentiate between "a=".split... and "a".split....

**Comment by jhass** [comment] 2015-08-17 08:25
`"a=".split("=")` returns `["a"]` in Ruby, which is inconsistent to specifying a limit. I guess we just went the wrong path towards consistency here and should make both cases return `["a", ""]`

**Comment by asterite** [comment] 2015-08-18 23:31
This is a duplicate of #1070

**Closed by asterite** 2015-08-18 23:31 UTC
