### ISSUE TITLE
Calls prior redefinition should call the original (Was: undefined method in proc)

### ISSUE THREAD

**Issue by kostya** [manastech/crystal#123] opened 2014-04-19 19:22 UTC
```ruby
class A
end

def some
  A.new.bla
end

v = ->some

class A
  def bla
    p :bla
  end
end

v.call
```

**Comment by asterite** [comment] 2015-10-18 13:51
I'll close this because it's basically a duplicate of #1104

**Closed by asterite** 2015-10-18 13:51 UTC
Labels: compiler, enhancement
