### ISSUE TITLE
Unbuffered Channel locks the process

### ISSUE THREAD

**Issue by askn** [manastech/crystal#1870] opened 2015-11-05 14:43 UTC
I wanted to test out Unbuffered Channels. This code compiles but it just locks the process. 

``` crystal
jobs = Channel(Int32).new
jobs.send i
puts jobs.receive
```

**Comment by ysbaddaden** [comment] 2015-11-05 14:44
Yes, on purpose, so it blocks in a coroutine, eg: `spawn { jobs.receive }`.

**Comment by asterite** [comment] 2015-11-05 14:55
Duplicate of https://github.com/manastech/crystal/issues/1866

Kind of... here it's unbuffered, the other is buffered. In Go:

```go
package main

func main() {
	ch := make(chan int)
	ch <- 1
	<-ch
}
```

```
go run goo.go 
fatal error: all goroutines are asleep - deadlock!
```

So both programs behave the same way: fatal error (crash vs. hang forever)

**Closed by asterite** 2015-11-05 14:55 UTC
