### ISSUE TITLE
Splat methods not called by super with keyword arguments

### ISSUE THREAD

**Issue by technorama** [manastech/crystal#1255] opened 2015-08-21 19:04 UTC
Problems areas are commented below.

Example:

```crystal
class A
  def initialize(a, @kw = nil)
    puts "a #{@kw}"
  end
end

class B < A
  #  sometimes not called!
  def initialize *args
    super *args
    puts "b #{args.inspect} !!!!!"
  end
end 

class C < B # TCPSocket
  def initialize
    super(1, 1) # working
    puts ""
    super(1, kw: 1) # broken
  end
end

C.new
```

**Comment by asterite** [comment] 2015-08-25 18:18
Splats and keyword arguments are incompatible right now. That means that `def initialize(*args)` doesn't match the `super(1, kw: 1)` call.

This is actually kind of a duplicate of #1033, where a super calls passes through a superclass if no initialize matches, but it should give an error in that case.

**Closed** 2015-09-10 19:04 UTC
Labels: bug, compiler
